Repository pytorch/test-infra, pull requests merged in 2021-09, with the labels that each got.

#113 Save URL for status events
  aws/lambda/github-webhook-rds-sync/utils.py
Labels: CLA Signed

#103 Add cuda install to base windows AMIs
  aws/ami/windows/README.md
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
  aws/ami/windows/variables.pkr.hcl
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed, aws

#114 Add download.pytorch.org CloudFront function code
  aws/websites/download.pytorch.org/README.md
  aws/websites/download.pytorch.org/pep503_whl_redirect.js
Labels: CLA Signed

#115 Clean up Grafana datasources
  aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/github.yml
  aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/metrics.yml
  aws/websites/metrics.pytorch.org/files/grafana-provisioning/datasources/mysql.yml
Labels: CLA Signed

#117 Update pep503_whl_redirect
  aws/websites/download.pytorch.org/pep503_whl_redirect.js
Labels: CLA Signed

#116 Add GHA to sync pytorch-canary
  .github/workflows/sync_pytorch_canary.yml
Labels: CLA Signed

#118 Fix to use nonbare clone
  .github/workflows/sync_pytorch_canary.yml
Labels: CLA Signed

#119 Fix sync-pytorch-canary by using force push
  .github/workflows/sync_pytorch_canary.yml
Labels: CLA Signed

#121 Add `workflow_dispatch` for metrics.pytorch.org
  .github/workflows/metrics_pytorch_org.yml
Labels: CLA Signed

#120 Make sync lambda reslient to schema changes
  .gitattributes
  aws/lambda/github-webhook-rds-sync/Makefile
  aws/lambda/github-webhook-rds-sync/existing_schema.py
  aws/lambda/github-webhook-rds-sync/lambda_function.py
  aws/lambda/github-webhook-rds-sync/utils.py
Labels: CLA Signed

#122 Update dashboards before deploying
  .github/scripts/generate_ci_workflows.py
  .github/templates/common.yml.j2
  .github/templates/metrics_pytorch_org.yml.j2
  .github/templates/update_grafana_dashboards.yml.j2
  .github/workflows/generated-metrics-pytorch-org.yml
  .github/workflows/generated-update-grafana-dashboards.yml
Labels: CLA Signed

#127 tools: Add clear_offline_runners utility
  .github/workflows/tools-self-hosted-runner-utils.yml
  tools/self-hosted-runner-utils/Makefile
  tools/self-hosted-runner-utils/README.md
  tools/self-hosted-runner-utils/clear_offline_runners.py
  tools/self-hosted-runner-utils/requirements.txt
Labels: CLA Signed, gha infra

#128 tools: Add check_runners_state.py
  tools/self-hosted-runner-utils/README.md
  tools/self-hosted-runner-utils/check_runners_state.py
  tools/self-hosted-runner-utils/clear_offline_runners.py
Labels: CLA Signed, gha infra

#129 Fix subnet assignment for swarm
  aws/websites/metrics.pytorch.org/install.yml
Labels: CLA Signed

#130 Clean up rds sync webhook
  aws/lambda/github-webhook-rds-sync/requirements.txt
  aws/lambda/github-webhook-rds-sync/utils.py
Labels: CLA Signed
