Repository pytorch/test-infra, pull requests merged in 2022-12, with the labels that each got.

#1202 Disable Windows Vision Test Workflows
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_windows.yml
Labels: CLA Signed

#1204 [log classifier] add rule for inductor model failure, get rid of api
  aws/lambda/log-classifier/ruleset.toml
  torchci/pages/api/classifier/rules.ts
Labels: CLA Signed

#1213 Fix disabled tests workflow
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#1208 track the line number where functions are defined
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/tests/api/test_ast.py
Labels: CLA Signed

#1211 render violations in the GitHub UI
  tools/stronghold/src/api/checker.py
Labels: CLA Signed

#1214 [Nova] Try to fix flaky checkout issues in binary builds
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#1188 Add panel for num commits
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/num_commits_master.sql
  torchci/rockset/commons/num_commits_master.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1187 Remove short revert printer and small bug fix
  torchci/rockset/commons/__sql/reverted_prs_with_reason.sql
  torchci/rockset/prodVersions.json
  torchci/scripts/reverts.py
Labels: CLA Signed

#1189 Fix for flaky marker on hud and change flaky jobs query
  torchci/lib/fetchHud.ts
  torchci/rockset/commons/__sql/flaky_workflows_jobs.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1135 Unify smoke test naming
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#1207 Add a table for log classifications
  torchci/pages/metrics.tsx
  torchci/rockset/metrics/__sql/log_captures_count.sql
  torchci/rockset/metrics/log_captures_count.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1219 Update scripts to ROCm5.3
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#1230 [Nova] Fix Linux Wheels CUDA/ROCm Versioning Issue
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#1233 Use channel to specify ROCM versions
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#1235 Do package install last
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#1238 Use package install last for macos
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#1241 Increase max_available for linux.12xlarge to 350
  .github/scale-config.yml
Labels: CLA Signed

#1243 Correctly identify error logs for Scribe upload failures
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1242 [Nova] Fix Anaconda Upload Issue
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/test_build_conda_linux_with_cuda.yml
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
Labels: CLA Signed

#1245 Change some log rules
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1197 Migrating to cuda 11.8
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#1259 Tweak scripts to support nvidia filtering on A10G instance
  .github/actions/setup-linux/action.yml
Labels: CLA Signed

#1264 Fix missing variable in previous commit
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1266 Fix release and test libtorch windows file names
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1271 Do not fail shutdown if no sshd is running
  .github/actions/teardown-windows/action.yml
Labels: CLA Signed

#1244 [Nova] More tests for Generic Linux job
  .github/workflows/test_linux_job.yml
Labels: CLA Signed

#1252 move the git fetch into the checker program
  .github/workflows/stronghold.yml
  tools/stronghold/src/api/checker.py
Labels: CLA Signed

#1253 group and suppress the fetch output by default
  tools/stronghold/src/api/checker.py
Labels: CLA Signed

#1270 tools: Add option to upload to base bucket
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  tools/pkg-helpers/pytorch_pkg_helpers/__main__.py
  tools/pkg-helpers/pytorch_pkg_helpers/conda.py
  tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
  tools/pkg-helpers/tests/test_macos.py
  tools/pkg-helpers/tests/test_wheel.py
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1276 Upload Path Fix
  tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
Labels: CLA Signed

#1231 Fix pytorchbot drci and add startup failures
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/lib/drciUtils.ts
  torchci/lib/fetchRecentWorkflows.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/commons/recent_pr_workflows_query.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#1258 add more instance types to test gpu
  .github/workflows/test_linux_job.yml
Labels: CLA Signed

#1279 Add stable vs candidate version for test vs release channel
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1280 Fix rebase help text
  torchci/lib/bot/cliParser.ts
Labels: CLA Signed

#1278 Comment and close disabled non-flaky issues
  torchci/lib/fetchDisabledNonFlakyTests.ts
  torchci/lib/types.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/rockset/commons/__sql/disabled_non_flaky_tests.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/disabled_non_flaky_tests.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/disableFlakyBot.test.ts
Labels: CLA Signed

#1220 Fix failures query
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/failure_samples_query.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1275 RetryBot enhancements: Better retry logic & Extend retry mechanism to PRs
  torchci/lib/bot/retryBot.ts
  torchci/test/retryBot.test.ts
Labels: CLA Signed

#1293 Lower the priority of scribe error in log classifier rule
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1287 Add basic classifications to drci
  torchci/lib/bot/utils.ts
  torchci/lib/drciUtils.ts
  torchci/lib/fetchRecentWorkflows.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/commit_failed_jobs.sql
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/commons/commit_failed_jobs.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#1296 Revert "RetryBot enhancements: Better retry logic & Extend retry mech… …anism to PRs (#1275)"
  torchci/lib/bot/retryBot.ts
  torchci/test/retryBot.test.ts
Labels: CLA Signed

#1292 Nova / TorchData / Fix smoke tests
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#1300 Bump stable version for release 1.13.1
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1246 More log classifier changes
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1297 Added env-var-script parameter to the build_wheels_linux workflow
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#1298 track the line number where a parameter is defined
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/tests/api/test_ast.py
Labels: CLA Signed

#1302 simplify parameter reordering check
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_compatibility.py
Labels: CLA Signed

#1304 no longer track position for each parameter
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_ast.py
  tools/stronghold/tests/api/test_compatibility.py
Labels: CLA Signed

#1311 Revert "no longer track position for each parameter"
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_ast.py
  tools/stronghold/tests/api/test_compatibility.py
Labels: CLA Signed

#1303 use difflib to better detect changes to positional parameters
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_compatibility.py
Labels: CLA Signed

#1312 [Reland] no longer track position for each parameter
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_ast.py
Labels: CLA Signed

#1309 [BE] `checkout@v2`->`checkout@v3`
  .github/templates/common.yml.j2
  .github/templates/deploy_lambda.yml.j2
  .github/templates/metrics_pytorch_org.yml.j2
  .github/workflows/backfill-workflow-job.yml
  .github/workflows/check-alerts.yml
  .github/workflows/clang-tidy-linux.yml
  .github/workflows/clang-tidy-macos.yml
  .github/workflows/generated-github-webhook-rds-sync.yml
  .github/workflows/generated-metrics-pytorch-org.yml
  .github/workflows/generated-rds-proxy.yml
  .github/workflows/generated-update-grafana-dashboards.yml
  .github/workflows/github-status-test-lambda.yml
  .github/workflows/lambda-runners.yml
  .github/workflows/lambda-webhook.yml
  .github/workflows/lambda_github_status_webhook_handler.yml
  .github/workflows/lambda_scribe_proxy.yml
  .github/workflows/lint.yml
  .github/workflows/lint_actions.yml
  .github/workflows/log-classifier-lambda.yml
  .github/workflows/push-rockset-query-lambda-tags.yml
  .github/workflows/sync_pytorch_canary.yml
  .github/workflows/test-setup-ssh.yml
  .github/workflows/tflint.yml
  .github/workflows/tools-self-hosted-runner-utils.yml
  .github/workflows/torchci.yml
  .github/workflows/update-drci-comments.yml
  .github/workflows/update-queue-times.yml
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#1314 Add ability to use comma separated values for packages
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1315 test and fix that adding optional parameters is ok
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_compatibility.py
Labels: CLA Signed

#1317 Require approval before attempting merges
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/fixtures/pull_request_reviews.json
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#1268 manage mac pet instances with terraform
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
  terraform-aws-github-runner/modules/runners/main.tf
  tools/self-hosted-runner-utils/.gitignore
  tools/self-hosted-runner-utils/check_runners_state_org.py
  tools/self-hosted-runner-utils/list-vpc-dependencies.sh
Labels: CLA Signed

#1322 Fix windows conda 22.11.0 regression
  aws/ami/windows/scripts/Installers/Install-Conda-Dependencies.ps1
Labels: CLA Signed, with-ssh

#1289 Mypy on reverts.py
  mypy.ini
  torchci/scripts/reverts.py
Labels: CLA Signed

#1325 RetryBot enhancements v2: Better retry logic & Extend retry mechanism to PRs
  torchci/lib/bot/retryBot.ts
  torchci/test/retryBot.test.ts
Labels: CLA Signed

#1323 [drci] fix cancelled workflows showing up
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1326 Classify groups of similar failures
  torchci/components/JobAnnotationToggle.tsx
  torchci/components/NavBar.tsx
  torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[annotation].ts
  torchci/pages/api/job_annotation/[repoOwner]/[repoName]/failures/[queryParams].ts
  torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/pages/flakyjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/commons/__sql/flaky_workflows_jobs.sql
  torchci/rockset/commons/flaky_workflows_jobs.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1327 Remove enabling non-flaky tests feature gating
  torchci/pages/api/flaky-tests/disable.ts
  torchci/rockset/commons/disabled_non_flaky_tests.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1333 ci: Add action to export matrix variables
  .github/actions/export-matrix-variables/action.yml
  .github/scripts/export_matrix_variables.py
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/test-export-matrix-variables.yml
  .github/workflows/test_linux_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#1336 [BE] Sort similar failures by recency
  torchci/pages/failure/[capture].tsx
Labels: CLA Signed

#1337 [BE] Streamline rockset query updating experience
  torchci/README.md
  torchci/scripts/downloadQueryLambda.mjs
Labels: CLA Signed

#1206 [Nova] Use windows.4xlarge and windows.8xlarge.nvidia.gpu for Windows wheel builds
  .github/workflows/build_wheels_windows.yml
  .github/workflows/test_build_wheels_windows_with_cuda.yml
  .github/workflows/test_build_wheels_windows_without_cuda.yml
Labels: CLA Signed

#1343 Check if rockset version is already correct when tagging prod
  torchci/scripts/pushRocksetTags.mjs
Labels: CLA Signed

#1344 Show rerun_disabled_tests failures as only warnings
  torchci/components/CommitStatus.tsx
  torchci/components/GroupJobConclusion.tsx
  torchci/components/JobConclusion.module.css
  torchci/components/JobConclusion.tsx
  torchci/components/JobSummary.tsx
  torchci/lib/JobClassifierUtil.ts
  torchci/lib/jobUtils.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#1346 Only close non-flaky issue if it hasn't been updated in 2 weeks
  torchci/lib/types.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/rockset/commons/__sql/issue_query.sql
  torchci/rockset/prodVersions.json
  torchci/test/disableFlakyBot.test.ts
  torchci/test/drci.test.ts
Labels: CLA Signed

#1345 Pin miniconda version, fixes vision and audio binary wheel builds
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed
