Repository pytorch/test-infra, pull requests merged in 2022-11, with the labels that each got.

#985 Enable test insights page for macos and rocm
  torchci/components/TestInsights.tsx
Labels: CLA Signed, module: rocm

#992 Only show status from push event on trunk HUD
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/commit_jobs_query.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#986 Jeanschmidt/lambda runners parallelism
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#988 Remove stale `% red jobs red on master` metric
  torchci/pages/metrics.tsx
Labels: CLA Signed

#996 Revert "Only show status from push event on trunk HUD"
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/commit_jobs_query.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#990 Comment on alert change
  .github/workflows/check-alerts.yml
  torchci/scripts/check_alerts.py
Labels: CLA Signed

#995 reference version over lambda alias
  terraform-aws-github-runner/modules/runners/scale-up.tf
Labels: CLA Signed

#997 Disable `ciflow/trunk` label on accept for 24 hours
  torchci/lib/bot/autoLabelBot.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed

#1001 pytorchbot: Label with ciflow/trunk only when attempting to merge
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#1000 fix provisioned concurrency by pushing a version
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
Labels: CLA Signed

#890 adds new LaunchTemplate for linux instances with Nvidia GPUs enabling its monitoring
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/logging.tf
  terraform-aws-github-runner/modules/runners/main.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/templates/cloudwatch_config_linux_nvidia.json
Labels: CLA Signed

#999 rewrite metrics CW to leverage dimensions and be compatible with meta infra
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
Labels: CLA Signed

#1003 [drci] Change to query from past 15 min to 30 min
  torchci/lib/drciUtils.ts
  torchci/lib/fetchRecentWorkflows.ts
Labels: CLA Signed

#1006 Avoid spamming for the same alert when its count increases
  torchci/scripts/check_alerts.py
Labels: CLA Signed

#935 [Nova] Adding new TorchText smoke tests to test build workflows
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows.yml
Labels: CLA Signed

#989 [Nova] Passing Torchvision Smoke Test to build workflow
  .github/workflows/build_conda_macos.yml
  .github/workflows/test_build_conda_linux_with_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_wheels_linux_with_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows.yml
Labels: CLA Signed

#977 [hud] show f for flaky
  torchci/components/GroupJobConclusion.tsx
  torchci/components/JobConclusion.module.css
  torchci/components/JobConclusion.tsx
  torchci/lib/JobClassifierUtil.ts
  torchci/lib/fetchHud.ts
  torchci/lib/types.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#939 remove old log classifier
  torchci/log_classifier/README.md
  torchci/log_classifier/backfill.py
  torchci/log_classifier/classify_log.py
  torchci/log_classifier/download_jenkins.py
  torchci/log_classifier/download_log.py
  torchci/pages/api/flaky-tests/flakytest.ts
Labels: CLA Signed

#1009 Show inductor jobs TTS
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/metrics/__sql/tts_duration_historical.sql
  torchci/rockset/metrics/__sql/tts_duration_historical_percentile.sql
  torchci/rockset/metrics/tts_duration_historical.lambda.json
  torchci/rockset/metrics/tts_duration_historical_percentile.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1004 add persistent grouping
  torchci/components/GroupJobConclusion.tsx
  torchci/lib/JobClassifierUtil.ts
  torchci/lib/types.ts
  torchci/lib/useHudData.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#1015 [hud] fix layout shift in HUD
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1016 Auth Suo into being able to classify failures
  torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[jobId]/[annotation].ts
Labels: CLA Signed

#1020 simplify pattern to include requirements.txt files in Git
  .gitignore
Labels: CLA Signed

#1017 Use fixed names for docs build jobs
  torchci/pages/metrics.tsx
Labels: CLA Signed

#1026 [hud] fix layout shift in minihud
  torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#1029 simplify pattern to include requirements.txt files in Git
  .gitignore
Labels: CLA Signed

#857 Create a lambda to aggregate usage logs
  aws/lambda/usage-log-aggregator/lambda_function.py
  aws/lambda/usage-log-aggregator/requirements.txt
  aws/lambda/usage-log-aggregator/test_lambda_function.py
  aws/lambda/usage-log-aggregator/test_samples/test_usage_log_1.txt
  aws/lambda/usage-log-aggregator/test_samples/test_usage_log_1.zip
Labels: CLA Signed

#1033 simplify pattern to include requirements.txt files in Git
  .gitignore
Labels: CLA Signed

#1035 specify mypy version via a text file, rather than in the workflow
  .github/workflows/lint.yml
  .mypy_requirements.txt
Labels: CLA Signed

#1036 run mypy if any requirements files change
  .github/workflows/lint.yml
Labels: CLA Signed

#1037 upgrade mypy to 0.982
  .mypy_requirements.txt
  aws/lambda/github-status-sync/requirements.txt
Labels: CLA Signed

#1043 ci: Update setup-linux to include latest driver install
  .github/actions/setup-linux/action.yml
  .github/workflows/test_linux_job.yml
Labels: CLA Signed

#1042 Use generic ci windows runners
  .github/workflows/windows_job.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1047 Exclude pytorch/pull/26921 from ciflow
  torchci/lib/bot/ciflowPushTrigger.ts
Labels: CLA Signed

#1050 Add name parameter to windows ci worker
  .github/workflows/test_windows_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#1051 Adding name parameter macos and linux ci workers
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/test_linux_job.yml
  .github/workflows/test_macos_job.yml
Labels: CLA Signed

#1013 Reduce the threshold to display test insights overview to 60s
  torchci/pages/tests.tsx
Labels: CLA Signed

#1053 Adding all option to get all the packages at once
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1052 Setup nvidia action
  .github/actionlint.yaml
  .github/actions/setup-linux/action.yml
  .github/actions/setup-nvidia/action.yml
  .github/workflows/test-setup-nvidia.yml
Labels: CLA Signed

#1038 fix requirements.txt enabling pattern in gitignore
  .gitignore
Labels: CLA Signed

#1040 add pip version to requirements
  tools/stronghold/requirements.txt
Labels: CLA Signed

#1041 add library to test API schema extraction from AST
  tools/stronghold/pyproject.toml
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/tests/api/test_ast.py
Labels: CLA Signed

#1044 remove no longer necessary test_dummy.py
  tools/stronghold/test_dummy.py
Labels: CLA Signed

#1045 use the recommended import mode "importlib"
  tools/stronghold/pyproject.toml
Labels: CLA Signed

#1061 run customized mypy for stronghold
  .github/workflows/stronghold.yml
  tools/stronghold/requirements.txt
Labels: CLA Signed

#1064 Add way to refresh Dr. CI results from HUD
  torchci/lib/bot/cliParser.ts
  torchci/lib/bot/drciBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/lib/drciUtils.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#1065 Update Windows pip dependencies for opt-einsum
  aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1
Labels: CLA Signed

#1027 tools: Add ability to clear org runners
  .github/workflows/lint.yml
  .github/workflows/tools-self-hosted-runner-utils.yml
  tools/self-hosted-runner-utils/check_runners_state.py
  tools/self-hosted-runner-utils/clear_offline_runners.py
  tools/self-hosted-runner-utils/requirements.txt
Labels: CLA Signed

#1076 Move inductor out of mem leak check group
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#1073 [Nova] Make workflow env vars available to pre and post scripts
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#1074 Clean up macos com.apple.coresymbolicationd
  .github/actions/setup-miniconda/action.yml
Labels: CLA Signed

#1077 Modifying generate binary build matrix. Prepare to migrate Pytorch core to this script
  .github/workflows/test_build_conda_linux_with_cuda.yml
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_linux_with_cuda.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1057 Add a new persistent group for rerunning disabled tests
  torchci/lib/JobClassifierUtil.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#1080 Add XPASS to log classifier
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1088 Adopt generate binary build matrix to call via main
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1091 Security update - remove dependency on py
  tools/pkg-helpers/poetry.lock
  tools/pkg-helpers/pyproject.toml
Labels: CLA Signed

#1090 Upgrade to secure version of minimatch & upgrade deprecated lambda nodejs12 runtime
  terraform-aws-github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock
  terraform-aws-github-runner/modules/webhook/webhook.tf
Labels: CLA Signed

#1092 Detect faulty ROCm runner in logs
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed, module: rocm

#1095 [Nova] Fix S3 upload path
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#1096 Don't match the echo command
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1097 Add linux.2xlarge.amd runner time
  .github/scale-config.yml
Labels: CLA Signed

#1084 Add pytest-flakefinder to Windows AMI
  aws/ami/windows/scripts/Installers/Install-Pip-Dependencies.ps1
Labels: CLA Signed

#1100 Migrate seemethere/add-github-ssh-key
  .gitattributes
  .github/actions/setup-ssh/action.yml
  .github/actions/setup-ssh/index.js
  .github/dependabot.yml
  .github/workflows/test-setup-ssh.yml
  .gitignore
  setup-ssh/.eslintignore
  setup-ssh/.eslintrc.json
  setup-ssh/.prettierignore
  setup-ssh/.prettierrc.json
  setup-ssh/README.md
  setup-ssh/__tests__/add-github-ssh-key.test.ts
  setup-ssh/__tests__/get-ip.test.ts
  setup-ssh/__tests__/github-utils.test.ts
  setup-ssh/jest.config.js
  setup-ssh/package.json
  setup-ssh/src/add-github-ssh-key.ts
  setup-ssh/src/ec2-utils.ts
  setup-ssh/src/get-ip.ts
  setup-ssh/src/github-utils.ts
  setup-ssh/src/main.ts
  setup-ssh/tsconfig.json
  setup-ssh/yarn.lock
Labels: CLA Signed

#1099 Update flaky test query
  torchci/rockset/commons/__sql/flaky_tests.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1067 adding minimal git client required to detect API changes
  tools/stronghold/src/api/git.py
  tools/stronghold/tests/api/test_git.py
Labels: CLA Signed

#1112 extract _to_source_file into a testing module
  tools/stronghold/pyproject.toml
  tools/stronghold/tests/api/test_ast.py
  tools/stronghold/tests/api/test_compatibility.py
  tools/stronghold/tests/lib/testing/__init__.py
  tools/stronghold/tests/lib/testing/source.py
Labels: CLA Signed

#1113 extract commit_file to a testing module
  tools/stronghold/tests/api/test_git.py
  tools/stronghold/tests/lib/testing/git.py
Labels: CLA Signed

#1093 Extend retrybot to trunk and *-binaries workflows
  torchci/lib/bot/retryBot.ts
  torchci/test/retryBot.test.ts
Labels: CLA Signed

#1094 Identify docker errors
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1114 extract the git_repo pytest fixture to the shared conftest
  tools/stronghold/tests/api/conftest.py
  tools/stronghold/tests/api/test_git.py
Labels: CLA Signed

#1115 add a function to check a git commit for API violations
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/tests/api/test_compatibility.py
  tools/stronghold/tests/lib/testing/git.py
Labels: CLA Signed

#1120 add a script to analyze git history for a repo
  tools/stronghold/bin/analyze-history
Labels: CLA Signed

#1089 Jeanschmidt - Add partially multi-region logic && separate VPCs for canary and main
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runner-binaries-syncer/variables.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/package.json
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
  terraform-aws-github-runner/modules/runners/main.tf
  terraform-aws-github-runner/modules/runners/outputs.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/outputs.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#1121 Revert "Upgrade to secure version of minimatch & upgrade deprecated lambda nodejs12 runtime"
  terraform-aws-github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock
  terraform-aws-github-runner/modules/webhook/webhook.tf
Labels: CLA Signed

#1130 Conda upload inside prepared environment
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#1102 Add a log classfifier rule for makefile build failure
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#1126 run the lint job if mypy.ini is modified
  .github/workflows/lint.yml
Labels: CLA Signed

#1129 Add `instructions` parameter to setup-ssh
  .github/actions/setup-ssh/action.yml
  .github/actions/setup-ssh/index.js
  .github/workflows/test-setup-ssh.yml
  setup-ssh/src/main.ts
Labels: CLA Signed

#1125 use mypy --strict
  aws/lambda/github-status-sync/lambda_function.py
  mypy.ini
Labels: CLA Signed

#1127 add program to run the API compatibility check
  tools/stronghold/src/api/checker.py
Labels: CLA Signed

#1131 Check for disk space first before setting up conda
  .github/actions/setup-miniconda/action.yml
Labels: CLA Signed

#1134 [setup-ssh][BE] Get rid of deprecated `rmdirSync`
  .github/actions/setup-ssh/index.js
  setup-ssh/src/add-github-ssh-key.ts
Labels: CLA Signed

#1145 Use pypi version for cuda 11.7 in release by default
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1118 Disable flaky tests across jobs
  torchci/lib/fetchFlakyTests.ts
  torchci/lib/types.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/rockset/commons/__sql/flaky_tests_across_jobs.sql
  torchci/rockset/commons/flaky_tests_across_jobs.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/disableFlakyBot.test.ts
Labels: CLA Signed

#1149 Add cpu, macos or windows and release channel to pypi default
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1150 Fix passing gpu_arch_version to get_wheel_install_command()
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1132 replace check_commit with check_range
  tools/stronghold/bin/analyze-history
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/src/api/git.py
  tools/stronghold/tests/api/test_git.py
Labels: CLA Signed

#1152 Pass os: str to get_wheel_install_command()
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1147 group Python environment setup output into its own section
  .github/workflows/stronghold.yml
Labels: CLA Signed

#1138 eliminate git.Repository.get_commit_info
  tools/stronghold/src/api/git.py
  tools/stronghold/tests/api/test_git.py
Labels: CLA Signed

#1140 parameterize the api checker on head and base commits
  tools/stronghold/src/api/checker.py
Labels: CLA Signed

#1146 Improved HUD (barcharts and joblist) failures page with branch information
  torchci/components/JobSummary.tsx
  torchci/lib/types.ts
  torchci/pages/failure/[capture].tsx
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#1157 Fix macos instructions for nightly and release
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1136 fix file path for conda macos upload
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#1156 allow customizing the linux_job docker image
  .github/workflows/linux_job.yml
  .github/workflows/test_linux_job.yml
Labels: CLA Signed

#1158 use smaller docker images for stronghold runs
  .github/workflows/stronghold.yml
Labels: CLA Signed

#1165 Add stable version to matrix, use generic linux runners
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1166 [BE] Sort the grouped failures in the failure view
  torchci/pages/failure/[capture].tsx
Labels: CLA Signed

#1169 Macos arm64 libtorch fix
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1177 Fix if statement for libtorch nightly linux and windows installs
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1168 Report all disabled tests that are not flaky anymore
  .github/scripts/update_disabled_tests.py
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#1178 Stop flakyjobs page from refreshing all the time
  torchci/pages/flakyjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#1181 Fix windows nightly libtorch
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1183 Fix windows nightly libtorch
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1184 Fix ident in if statement made by previous commit (typo)
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1182 Fix mem leak check group
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#1180 Fix accept2ship now that we don't use -l
  torchci/lib/bot/acceptBot.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#1144 Fixes to correctly assign the security group to the ec2 runner
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/main.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#1186 Add continue on error input param to generic jobs
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#1185 Remove unused VPC and SecGroup after layout migration
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
  terraform-aws-github-runner/modules/runners/main.tf
  terraform-aws-github-runner/modules/runners/scale-down.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#1163 use a smaller image for the api compatibility check
  .github/workflows/stronghold.yml
Labels: CLA Signed

#1164 decrease runner size to linux.large for Stronghold CI
  .github/workflows/stronghold.yml
Labels: CLA Signed

#1159 write to GITHUB_STEP_SUMMARY in stronghold commands
  .github/workflows/stronghold.yml
Labels: CLA Signed

#1137 Cat the output of pytorch-pkg-helpers
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#1160 [Nova] Fix call to anaconda during upload in Mac Conda builds
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#1190 Remove conda cpuonly flag for macos installs
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1193 Remove extra space when no conda_package_type specified
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#1194 [Nova] Torchtext pre-script
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows.yml
Labels: CLA Signed

#1191 [Nova] Continue workflow even if upload artifact fails due to network error
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#1199 [Nova] Add new Vision pre-scripts to the test builds
  .github/workflows/test_build_wheels_linux_with_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
Labels: CLA Signed

#1205 fix: add cleanup step prior to checkout
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed, Nova Tooling
