Repository pytorch/test-infra, pull requests merged in 2023-10, with the labels that each got.

#4605 Update kpi queries to use created time instead of rockset injestion time
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/prodVersions.json
  torchci/rockset/pytorch_dev_infra_kpis/__sql/num_reverts.sql
  torchci/rockset/pytorch_dev_infra_kpis/__sql/number_of_force_pushes_historical.sql
  torchci/rockset/pytorch_dev_infra_kpis/number_of_force_pushes_historical.lambda.json
Labels: CLA Signed

#4603 [dr ci] Query rockset for PR body
  torchci/lib/bot/drciBot.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#4604 [dr ci] Include workflow name in job name
  torchci/lib/drciUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4608 rename models in benchmark dashboard's model mapping
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4611 Advance binary build matrix for release 2.1
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#4610 [dr ci] Fix too many jobs getting removed by `removeCancelledJobAfterRetry`
  torchci/lib/drciUtils.ts
  torchci/lib/fetchCommit.ts
  torchci/lib/fetchRecentWorkflows.ts
  torchci/lib/jobUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/commit_failed_jobs.sql
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#4613 [TorchFix] Make pretrained rule work when a model imported from a submodule
  tools/torchfix/tests/fixtures/vision/checker/pretrained.py
  tools/torchfix/tests/fixtures/vision/codemod/pretrained_submodule_import.py
  tools/torchfix/tests/fixtures/vision/codemod/pretrained_submodule_import.py.out
  tools/torchfix/torchfix/visitors/vision/__init__.py
Labels: CLA Signed

#4616 Fix aarch64 install instruction in release. Add script to update matrix tests
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/update_test_assets.sh
Labels: CLA Signed

#4615 [TorchFix] add visitor for deprecated TorchVision transform
  tools/torchfix/tests/fixtures/vision/checker/to_tensor.py
  tools/torchfix/tests/fixtures/vision/checker/to_tensor.txt
  tools/torchfix/torchfix/torchfix.py
  tools/torchfix/torchfix/visitors/vision/__init__.py
  tools/torchfix/torchfix/visitors/vision/pretrained.py
  tools/torchfix/torchfix/visitors/vision/to_tensor.py
Labels: CLA Signed

#4541 Update README.md
  README.md
Labels: CLA Signed

#4620 Fix lintrunner MacOS builds
  .github/workflows/lintrunner_ci.yml
Labels: CLA Signed

#4617 TD: Export TestClass correlations
  .github/workflows/update_test_file_ratings.yml
  torchci/scripts/calculate_file_test_rating.py
  torchci/scripts/test_calculate_file_test_rating.py
Labels: CLA Signed

#4621 Add the workflow name as an optional search parameter
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/pages/api/search.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4622 Classify infra failures without any associated runners as flaky
  torchci/lib/drciUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/commit_failed_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4626 Add an option to pass secrets to Nova MacOS job
  .github/scripts/run_docker_with_env_secrets.py
  .github/scripts/run_with_env_secrets.py
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/test_linux_job.yml
  .github/workflows/test_macos_job.yml
  .github/workflows/tests.yml
Labels: CLA Signed

#4627 Add `linux.12xlarge.ephemeral`
  .github/scale-config.yml
Labels: CLA Signed

#4606 Revert "Pin conda build images - fix nightly conda failures (#4582)"
  .github/actions/setup-binary-builds/action.yml
  .github/workflows/build_conda_linux.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
Labels: CLA Signed, with-ssh

#4628 Remove use linux.t4g.2xlarge
  .github/workflows/linux_job.yml
Labels: CLA Signed

#4630 Removed condition for linux.t4g.2xlarge
  .github/workflows/linux_job.yml
Labels: CLA Signed

#4631 Restore special case for python 3.11 in setup-binary-builds. Fix tensorrt
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#4624 TD: Denoise TTRS metric
  torchci/pages/kpis.tsx
  torchci/rockset/prodVersions.json
  torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql
  torchci/rockset/pytorch_dev_infra_kpis/ttrs_percentiles.lambda.json
Labels: CLA Signed

#4634 [dr ci] Fix dup jobs?
  torchci/lib/jobUtils.ts
Labels: CLA Signed

#4636 Add an excluded list for flaky detection on Dr.CI
  torchci/lib/drciUtils.ts
  torchci/test/drci.test.ts
Labels: CLA Signed

#4629 add buttons to rate logs
  torchci/components/LogAnnotationToggle.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/types.ts
  torchci/pages/api/log_annotation/[repoOwner]/[repoName]/[annotation].ts
Labels: CLA Signed

#4638 Add doc build jobs into the excluded list
  torchci/lib/drciUtils.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4625 [TorchFix] Update version to 0.1.0
  tools/torchfix/README.md
  tools/torchfix/torchfix/torchfix.py
Labels: CLA Signed

#4641 [TorchFix] Fix bug in TorchVisionDeprecatedToTensorVisitor with ImportStar
  tools/torchfix/tests/fixtures/vision/checker/to_tensor.py
  tools/torchfix/torchfix/torchfix.py
  tools/torchfix/torchfix/visitors/vision/to_tensor.py
Labels: CLA Signed

#4649 Add the list of previous commands as optional context on log classifier
  aws/lambda/log-classifier/fixtures/request.json
  aws/lambda/log-classifier/src/main.rs
  aws/lambda/log-classifier/src/rule_match.rs
Labels: CLA Signed

#4637 add ability to view multiple focused log lines at once
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/annotated_flaky_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/failed_workflow_jobs.sql
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/commons/weekly_force_merge_stats.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_check_alerts.py
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4652 Revert "add ability to view multiple focused log lines at once (#4637)"
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/annotated_flaky_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/failed_workflow_jobs.sql
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/commons/weekly_force_merge_stats.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_check_alerts.py
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4654 Add executorch to hud navbar
  torchci/components/NavBar.tsx
  torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
Labels: CLA Signed

#4656 Expose Dr.CI classification results as a check run summary
  torchci/pages/api/drci/drci.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#4655 Apply lint to aws directory
  .github/workflows/lint.yml
  aws/lambda/github-webhook-rds-sync/generate_schema.py
  aws/lambda/github-webhook-rds-sync/lambda_function.py
  aws/lambda/github-webhook-rds-sync/test_lambda.py
  aws/lambda/github-webhook-rds-sync/utils.py
  aws/lambda/log-classifier/src/main.rs
  aws/lambda/log-classifier/src/rule_match.rs
  aws/lambda/rds-proxy/lambda_function.py
  aws/lambda/usage-log-aggregator/lambda_function.py
Labels: CLA Signed

#4658 Only upload Dr.CI classification results for the target PR
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#4657 [reland] add ability to view multiple focused log lines at once
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/annotated_flaky_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/failed_workflow_jobs.sql
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/commons/weekly_force_merge_stats.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_check_alerts.py
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4659 Revert "[reland] add ability to view multiple focused log lines at on…
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/annotated_flaky_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/failed_workflow_jobs.sql
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/commons/weekly_force_merge_stats.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_check_alerts.py
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4647 Add an auto-label rule for ciflow/rocm
  torchci/lib/bot/autoLabelBot.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed, module: rocm

#4661 [BE] HUD can show jobs run on a PR against commits before it was rebased
  torchci/lib/fetchPR.ts
  torchci/rockset/commons/__sql/pr_commits.sql
  torchci/rockset/commons/pr_commits.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4660 "[reland] [reland] add ability to view multiple focused log lines at on… (#4659)"
  torchci/components/FilteredJobList.tsx
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/pages/metrics.tsx
  torchci/rockset/commons/__sql/annotated_flaky_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/failed_workflow_jobs.sql
  torchci/rockset/commons/__sql/failure_samples_query.sql
  torchci/rockset/commons/__sql/hud_query.sql
  torchci/rockset/commons/annotated_flaky_jobs.lambda.json
  torchci/rockset/commons/hud_query.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_check_alerts.py
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4664 [HUD] Group artifacts under job
  torchci/components/WorkflowBox.tsx
Labels: CLA Signed

#4666 Fix HUD when there is no captured failure
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#4667 Only query for similar non-success jobs
  torchci/lib/searchUtils.ts
Labels: CLA Signed

#4590 [TD] Historical edited files and profiling heuristics
  .github/workflows/update_test_file_ratings.yml
  .gitignore
  torchci/scripts/get_merge_base_info.py
  torchci/scripts/rockset_utils.py
  torchci/scripts/td_heuristic_historical_edited_files.py
  torchci/scripts/td_heuristic_profiling.py
  torchci/scripts/utils.py
  torchci/scripts/utils_td_heuristics.py
Labels: CLA Signed

#4670 [TD] Collect test class durations
  .github/workflows/update-test-times.yml
  torchci/rockset/commons/__sql/test_time_per_class.sql
  torchci/rockset/commons/__sql/test_time_per_class_periodic_jobs.sql
  torchci/rockset/commons/test_time_per_class.lambda.json
  torchci/rockset/commons/test_time_per_class_periodic_jobs.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/test_update_test_times.py
  torchci/scripts/update_test_times.py
Labels: CLA Signed

#4668 Use OpenSearch cluster to power "more like this" failure search
  torchci/components/JobLinks.tsx
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/pages/api/failure.ts
  torchci/pages/api/failure/[capture].ts
  torchci/pages/failure.tsx
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4673 Add ExecuTorch to Dr. CI
  .github/workflows/update-drci-comments.yml
  torchci/lib/bot/utils.ts
Labels: CLA Signed

#4674 [BE] Make add-github-ssh-key tolerant to errors
  .github/actions/setup-ssh/index.js
  setup-ssh/src/add-github-ssh-key.ts
  setup-ssh/src/github-utils.ts
Labels: CLA Signed

#4676 [setup-ssh] Handle errors in fetching labels
  .github/actions/setup-ssh/index.js
  setup-ssh/src/main.ts
Labels: CLA Signed

#4678 Advance candidate version for minor release
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#4677 Fix the number of hooks conditionally rendered by hasArtifacts
  torchci/components/WorkflowBox.tsx
  torchci/lib/searchUtils.ts
Labels: CLA Signed

#4671 [TorchFix] Add TorchUnsafeLoadVisitor
  tools/torchfix/tests/fixtures/security/checker/load.py
  tools/torchfix/tests/fixtures/security/checker/load.txt
  tools/torchfix/torchfix/torchfix.py
  tools/torchfix/torchfix/visitors/security/__init__.py
Labels: CLA Signed

#4680 [TorchFix] Deprecated codemods to honor aliases
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/aliased_import.py
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/aliased_import.py.out
  tools/torchfix/torchfix/common.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/chain_matmul.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/cholesky.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/qr.py
Labels: CLA Signed

#4682 Increase max runners for 'linux.arm64.2xlarge' to 200
  .github/scale-config.yml
Labels: CLA Signed

#4684 [HUD] Make artifacts inline again
  torchci/components/WorkflowBox.tsx
Labels: CLA Signed

#4685 Add an option to limit failures search to a specific branch
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/pages/api/search.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4681 Count models with 0 speedup as failures
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4686 [bot] Cancel pending workflows when PR is closed by non mergebot
  .gitignore
  torchci/lib/bot/cancelWorkflowsOnCloseBot.ts
  torchci/lib/bot/index.ts
  torchci/test/cancelWorkflowsOnCloseBot.test.ts
  torchci/test/fixtures/pull_request.closed.json
Labels: CLA Signed
