Repository pytorch/test-infra, pull requests merged in 2023-12, with the labels that each got.

#4774 [Nova] Do not install conda-build for wheels
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#4777 Update clang-tidy to 17.0.6
  .github/workflows/clang-tidy-linux.yml
  .github/workflows/clang-tidy-macos.yml
  tools/clang-tidy-checks/17.x-patches/0003-Do-not-use-pthread_rwlock_wrlock.diff
  tools/clang-tidy-checks/Dockerfile.cilint-clang-tidy
  tools/clang-tidy-checks/setup.sh
Labels: CLA Signed

#4776 Compare failure context in addition to the failure itself
  torchci/lib/drciUtils.ts
  torchci/lib/jobUtils.ts
  torchci/lib/searchUtils.ts
  torchci/lib/types.ts
  torchci/rockset/commons/__sql/commit_failed_jobs.sql
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/commons/commit_jobs_query.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#4779 Compare username in addition to email when checking similar failures
  torchci/lib/getAuthors.ts
  torchci/lib/jobUtils.ts
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#4781 Allowing closing or prs and issues through pytorchbot
  torchci/lib/bot/cliParser.ts
  torchci/lib/bot/pytorchBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/closeCommands.test.ts
  torchci/test/labelCommands.test.ts
Labels: CLA Signed

#4788 Handle null machine_type for queued_jobs queries
  torchci/rockset/metrics/__sql/queued_jobs.sql
  torchci/rockset/metrics/__sql/queued_jobs_by_label.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4783 [dashboard] Exclude model_fail_to_load and eager_fail_to_run
  torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4794 backfill-workflow-job.yml to use OIDC to authenticate to AWS
  .github/workflows/backfill-workflow-job.yml
  torchci/scripts/backfillJobs.mjs
Labels: CLA Signed

#4795 Expose dynamo peak CUDA memory usage
  torchci/lib/types.ts
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
  torchci/pages/benchmark/compilers.tsx
  torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql
  torchci/rockset/inductor/compilers_benchmark_performance.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4799 Handle false positive flaky detection on reverted PRs
  torchci/lib/drciUtils.ts
  torchci/lib/jobUtils.ts
  torchci/lib/searchUtils.ts
  torchci/pages/api/failure.ts
  torchci/test/drciUtils.test.ts
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#4804 Specific PYTORCH_VERSION when building RC for test channel
  .github/actions/set-channel/action.yml
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#4803 Specific PYTORCH_VERSION when building RC for test channel
  .github/actions/set-channel/action.yml
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#4806 Add constraint for version to conda build when in test channel
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
Labels: CLA Signed

#4805 Add constraint for version to conda build when in test channel
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
Labels: CLA Signed

#4800 [hud] Tracking experiment
  torchci/lib/track.ts
  torchci/pages/_app.tsx
  torchci/pages/api/track.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#4808 Increase Dynamo shard time for test_ops.py to 3.5x of the current amount
  stats/test-times.json
Labels: CLA Signed

#4807 fixing backfillJobs.mjs script, skipping entries that are too old to be retrieved in GH API
  torchci/scripts/backfillJobs.mjs
Labels: CLA Signed

#4810 Add ciflow/trunk to reviewed prs
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed

#4812 [hud] Tracking experiment: add a session id
  torchci/lib/track.ts
Labels: CLA Signed

#4814 Advance stable release to 2.1.2
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#4802 [oidc] Update slow test workflow switch to oidc
  .github/workflows/update-slow-tests.yml
Labels: CLA Signed

#4822 Give slow tests update workflow write perms to repo contents
  .github/workflows/update-slow-tests.yml
Labels: CLA Signed

#4823 Add workflow call to pr dependencies check
  .github/workflows/pr-dependencies-check.yml
Labels: CLA Signed

#4824 use inputs instead of github.events.inputs as the latter does not work for workflow calls
  .github/workflows/pr-dependencies-check.yml
Labels: CLA Signed

#4826 [releng] Advance rocm to 5.6 and 5.7 in test channel
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#4813 Allow specifing PyTorch version when validating domain libraries
  .github/scripts/install_torch.sh
  .github/workflows/validate-domain-library.yml
Labels: CLA Signed

#4832 [CI] Automate clang-format building
  .github/workflows/clang-tidy-linux.yml
  .github/workflows/clang-tidy-macos.yml
  tools/clang-tidy-checks/setup.sh
Labels: CLA Signed

#4825 let pr-dependencies-check throw an error if a pr is not mergable
  .github/workflows/pr-dependencies-check.yml
Labels: CLA Signed

#4833 [hud] Tracking: switch to Google Analytics
  torchci/lib/track.ts
  torchci/package.json
  torchci/pages/_app.tsx
  torchci/pages/api/track.ts
  torchci/yarn.lock
Labels: CLA Signed

#4834 Enable nightly 3.12 for all domains
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, ciflow/binaries/all

#4839 [oidc] Update linux wheels job to use oidc
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4840 Revert "[oidc] Update linux wheels job to use oidc"
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4831 Support fuzzy string matching to compare failure context
  torchci/lib/jobUtils.ts
  torchci/package.json
  torchci/test/jobUtils.test.ts
  torchci/yarn.lock
Labels: CLA Signed

#4841 Revert "Revert "[oidc] Update linux wheels job to use oidc" (#4840)"
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4842 Revert "Revert "Revert "[oidc] Update linux wheels job to use oidc" (#4840)""
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4844 Add python 3.12 to test environment
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#4843 Enable nightly 3.12 for all domains
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
Labels: CLA Signed

#4782 Rerequest review on pr closure
  torchci/lib/bot/index.ts
  torchci/lib/bot/stripApprovalBot.ts
  torchci/test/fixtures/pull_request.reopened.json
  torchci/test/fixtures/pull_request_review_approved.json
  torchci/test/stripApprovals.test.ts
Labels: CLA Signed

#4846 Fix obsolete recent example links
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#4848 Improve wording in the dependencies check workflow
  .github/workflows/pr-dependencies-check.yml
Labels: CLA Signed

#4849 [CI] Limit libtorch builds to shared-with-dep
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#4851 Binary build matrix. Add macos arm64 libtorch builds. Fix macos x86 filename
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed
