Repository pytorch/test-infra, pull requests merged in 2023-02, with the labels that each got.

#1967 Update test times to update old json instead of making new json
  torchci/scripts/updateTestTimes.mjs
Labels: CLA Signed

#1999 improve retry mechanism, avoiding rely on AWS SQS retry and instead o…
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#2019 clean messages from sqs when there is a failure
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#2037 Remove CUDA 11.6 from binary matrix
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2038 [ez] Remove pytorch-bot comments from revert generator
  torchci/rockset/commons/__sql/reverted_prs_with_reason.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#2100 Require at least 6GB on MacOS M1 runner
  .github/actions/check-disk-space/action.yml
Labels: CLA Signed

#2102 Clear conda and pip cache when low disk space on MacOS M1 pet runners
  .github/actions/check-disk-space/action.yml
Labels: CLA Signed

#2107 Fix typo in variable name WITH_FLAKY_TEST_ALERT in check-alerts.yml
  .github/workflows/check-alerts.yml
Labels: CLA Signed

#2109 Support an optional job name filter (regex) in the OSS alerting
  torchci/scripts/check_alerts.py
  torchci/scripts/test_check_alerts.py
Labels: CLA Signed

#2442 gha-infra: Revert retry related commits
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
  terraform-aws-github-runner/modules/runners/policies/lambda-scale-up.json
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed, gha infra

#2448 Revert "fail scale-up batch when a single instance of the batch fails"
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#2441 Add a % red on trunk metric with retry
  torchci/lib/rockset.ts
  torchci/pages/metrics.tsx
  torchci/rockset/metrics/__sql/master_commit_red_avg.sql
  torchci/rockset/metrics/__sql/workflow_duration_avg.sql
  torchci/rockset/metrics/__sql/workflow_duration_percentile.sql
  torchci/rockset/metrics/master_commit_red_avg.lambda.json
  torchci/rockset/metrics/workflow_duration_avg.lambda.json
  torchci/rockset/metrics/workflow_duration_percentile.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#2529 Add fetch-depth option to all jobs
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#2105 Python 3.11 wheels builds
  .github/actions/setup-binary-builds/action.yml
  .github/workflows/test_build_wheels_linux_with_cuda.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2599 Restrict windows builds to one python one cuda version
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2614 Restrict windows builds to one python one cuda version
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2593 Exclude Py 3.11 from Nova Conda builds for now
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2616 Remove duplicated 3.11 config from generated matrix
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2678 Remove with py311 flag since python 3.11 was integrated
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2680 [generate binary matrix] Fix python logic
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#2682 Remove numpy from default install since not available for 3.11 python
  .github/scripts/install_torch.sh
Labels: CLA Signed

#2615 [kpis] Add reverts categories for revert chart
  torchci/pages/kpis.tsx
  torchci/rockset/prodVersions.json
  torchci/rockset/pytorch_dev_infra_kpis/__sql/num_reverts.sql
Labels: CLA Signed

#2689 Use smooth charts
  torchci/components/metrics/panels/TimeSeriesPanel.tsx
Labels: CLA Signed

#2681 Wheel size validation using https://download.pytorch.org/whl/ index
  .github/workflows/check-alerts.yml
  .github/workflows/test-binary-size-validation.yml
  tools/binary_size_validation/README.md
  tools/binary_size_validation/binary_size_validation.py
  tools/binary_size_validation/requirements.txt
  tools/binary_size_validation/test_binary_size_validation.py
  torchci/scripts/check_alerts.py
Labels: CLA Signed

#2686 Remove `conda-build` from setup-miniconda action
  .github/actions/setup-miniconda/README.md
  .github/actions/setup-miniconda/action.yml
  .github/workflows/test-setup-miniconda.yml
Labels: CLA Signed

#2690 Remove viable/strict lag per commit chart
  torchci/pages/kpis.tsx
Labels: CLA Signed

#2691 Migrate anaconda prune from pytorch to test-infra
  .github/scripts/anaconda-prune/prune.sh
  .github/scripts/anaconda-prune/run.sh
  .github/workflows/_prune-anaconda-packages.yml
  .github/workflows/anaconda-prune.yml
Labels: CLA Signed

#2756 Upload disabled tests condensed and slow tests to s3
  .github/workflows/update-slow-tests.yml
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#2685 Highlight selected jobs on reliability metric page
  torchci/components/hud.module.css
  torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/metrics/__sql/master_commit_red_percent_groups.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#2891 [Nova] Test conda package dependencies
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#2731 Build conda linux for domains. Run smoke tests in separate conda environment in Linux
  .github/workflows/build_conda_linux.yml
  aws/ami/windows/build.hwm
  aws/ami/windows/build.pwd
  aws/ami/windows/build.pwi
Labels: CLA Signed, with-ssh

#1290 Update generate_binary_build_matrix.py to ROCm 5.4.2
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#2516 Setting CHANNEL correctly for RC branches in Reusable Workflows
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#3527 Change python 3.11 wheel install command, to include domains install
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#3765 Temporarily disable alert checking in builder/builder
  .github/workflows/check-alerts.yml
Labels: CLA Signed

#3766 Only fetch alerts belong to the target repo and branch
  torchci/scripts/check_alerts.py
  torchci/scripts/test_check_alerts.py
Labels: CLA Signed

#3768 Re-enable alert checking in pytorch/builder
  .github/workflows/check-alerts.yml
Labels: CLA Signed

#3482 Add conda 3.11 builds for Linux
  .github/actions/setup-binary-builds/action.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#3769 Use same conda run env to upload to anaconda rather then creating new one
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#3770 Add alerts for cron/release validation workflows
  .github/workflows/check-alerts.yml
  torchci/scripts/check_alerts.py
  torchci/scripts/test_check_alerts.py
Labels: CLA Signed

#3556 Breakdown CI reliability metric into categories
  torchci/components/FilteredJobList.tsx
  torchci/components/JobAnnotationToggle.tsx
  torchci/components/metrics/panels/TablePanel.tsx
  torchci/lib/metricUtils.ts
  torchci/lib/types.ts
  torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
  torchci/rockset/commons/__sql/master_commit_red_jobs.sql
  torchci/rockset/commons/master_commit_red_jobs.lambda.json
  torchci/rockset/prodVersions.json
  torchci/test/metricUtils.test.ts
Labels: CLA Signed

#3774 [Nova] Test conda deps MacOS edition
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#3739 Read ciflow labels from config
  torchci/lib/bot/ciflowPushTrigger.ts
  torchci/lib/bot/utils.ts
  torchci/test/ciflow-push-trigger.test.ts
Labels: CLA Signed

#3775 Update test channel remove restriction on 3.11
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#3776 Fix regex for highlighting force merged PRs on hud
  torchci/rockset/commons/__sql/filter_forced_merge_pr.sql
  torchci/rockset/commons/filter_forced_merge_pr.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#3778 [Nova] Don't constraint 3.11 builds to mkl=2021
  tools/pkg-helpers/pytorch_pkg_helpers/__main__.py
  tools/pkg-helpers/pytorch_pkg_helpers/macos.py
Labels: CLA Signed

#3777 Add malfet channel to torch install instructions
  .github/scripts/install_torch.sh
Labels: CLA Signed

#3773 No-test build for Mac 3.11 conda build to Enable Vision/Audio
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#3779 Fix macos upload step
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#3780 Fix Macos and M1 upload folder
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#3781 Fix smoke test channel for MacOS
  .github/workflows/build_conda_macos.yml
Labels: CLA Signed

#3786 Fix python 3.11 wheel builds
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#3789 move disable flaky tests workflow to newer runner
  .github/workflows/disable-flaky-tests.yml
Labels: CLA Signed

#3790 Update ubuntu-18.04 to 22.04
  .github/workflows/check-alerts.yml
  .github/workflows/update-drci-comments.yml
Labels: CLA Signed

#3791 Upgrade next-auth to be compatible with node 18
  torchci/.env.example
  torchci/package.json
  torchci/types/next-auth-d.ts
  torchci/yarn.lock
Labels: CLA Signed

#3784 Update the list of disabled jobs
  .github/scripts/test_update_disabled_issues.py
  .github/scripts/update_disabled_issues.py
  .github/scripts/update_disabled_tests.py
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#3795 [BE] Sort hud groups intelligently
  torchci/lib/JobClassifierUtil.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#3797 [BE] Make skipped jobs more distinct from successful jobs
  torchci/components/GroupJobConclusion.tsx
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#3798 Only allow users with write permission to disable jobs
  .github/scripts/test_update_disabled_issues.py
  .github/scripts/update_disabled_issues.py
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#3799 Dr CI to link to hud, scroll to anchor link
  torchci/components/FilteredJobList.tsx
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
Labels: CLA Signed

#3792 set-output command is deprecated
  .github/actions/setup-linux/action.yml
Labels: CLA Signed

#3802 improve metrics.tts_percentile query
  torchci/rockset/metrics/__sql/tts_percentile.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#3800 Update bot to handle disabled job issue
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#3804 tools: mirror pytorch-triton-rocm
  tools/mirror-pypi/mirror_pytorch_triton_rocm.sh
Labels: CLA Signed, module: rocm

#3801 Use PyTorch bot token when checking for write permission
  .github/scripts/update_disabled_issues.py
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#3809 [hud] Add highlight when clicking on cells
  torchci/components/GroupHudTableHeaders.tsx
  torchci/components/GroupJobConclusion.tsx
  torchci/components/TooltipTarget.tsx
  torchci/components/hud.module.css
  torchci/lib/types.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#3813 Fix conda and wheel upload logic for test channel
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#3810 Fix backfill
  torchci/scripts/backfillJobs.mjs
Labels: CLA Signed
