Repository pytorch/test-infra, pull requests merged in 2023-07, with the labels that each got.

#4336 [TorchFix] Update cholesky to linalg.cholesky
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/cholesky.py
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/cholesky.py.out
  tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/cholesky.py
Labels: CLA Signed

#4337 Add retry mechanism before using conda for the first time
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed, with-ssh

#4338 Don't use ``bash -l {0}`` for setup-binary-builds initial steps
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#4339 Setup miniconda for linux conda builds
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#4340 PT2 dashboard: Highlight speedup as red if a model started failing to run
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
Labels: CLA Signed

#4344 Fix smoke tests for macos arm64
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#4343 Update for disable tests flaky from file reruns
  torchci/lib/fetchFlakyTests.ts
  torchci/pages/api/flaky-tests/disable.ts
Labels: CLA Signed

#4346 Add no-sudo option to linux_job. Required for aarch64 builds
  .github/workflows/linux_job.yml
Labels: CLA Signed

#4347 Use different alpine images for aarch64 linux builds
  .github/actions/chown-directory/action.yml
  .github/workflows/linux_job.yml
Labels: CLA Signed

#4345 Expose gpus from docker in cuda-based build pipelines
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4348 Trigger nightly builds (text only)
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4350 Trigger nightly builds (text only)
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4349 Fix gpu pass-though
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4341 [TorchFix] Fix mypy errors and add workflow
  .github/workflows/test-torchfix.yml
  tools/torchfix/pyproject.toml
  tools/torchfix/requirements-dev.txt
  tools/torchfix/torchfix/__main__.py
  tools/torchfix/torchfix/common.py
  tools/torchfix/torchfix/torchfix.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/cholesky.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/range.py
Labels: CLA Signed

#4354 Trigger nightly builds (text only)
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4357 Trigger inductor-periodic workflow on HUD
  torchci/components/WorkflowDispatcher.tsx
Labels: CLA Signed

#4355 Enforce yarn format
  .github/workflows/torchci.yml
  torchci/pages/nightlies.tsx
Labels: CLA Signed

#4241 Enable per-test copyable reproduction links on HUD
  torchci/components/JobLinks.tsx
  torchci/components/ReproductionCommand.tsx
Labels: CLA Signed

#4366 Update linux cuda driver to 535.54.03
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#4333 Disable bot to add labels based on platforms
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/test/disableFlakyBot.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#4353 Remove shard ID and unstable suffix when comparing failed job names with the base commit
  torchci/lib/jobUtils.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#4352 [TorchFix] Add torch.qr codemod
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/qr.py
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/qr.py.out
  tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/qr.py
Labels: CLA Signed

#4356 [TorchFix] Add chain_matmul codemod
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/chain_matmul.py
  tools/torchfix/tests/fixtures/deprecated_symbols/codemod/chain_matmul.py.out
  tools/torchfix/torchfix/visitors/deprecated_symbols/__init__.py
  tools/torchfix/torchfix/visitors/deprecated_symbols/chain_matmul.py
Labels: CLA Signed

#4369 Add ssh wiki to log
  .github/actions/setup-ssh/index.js
  setup-ssh/package.json
  setup-ssh/src/main.ts
  setup-ssh/yarn.lock
Labels: CLA Signed

#4368 Add docker failures to nightly HUD page. Change org of nightly page
  torchci/pages/nightlies.tsx
  torchci/rockset/nightlies/__sql/docker_jobs_red.sql
  torchci/rockset/nightlies/__sql/docker_jobs_red_past_day.sql
  torchci/rockset/nightlies/docker_jobs_red.lambda.json
  torchci/rockset/nightlies/docker_jobs_red_past_day.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4375 Make sure the nightly trigger executes on schedule
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4378 Nightly builds for vision and audio. Move trigger nightly to action
  .github/actions/trigger-nightly/action.yml
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4379 Nightly builds for vision and audio. Move trigger nightly to action
  .github/actions/trigger-nightly/action.yml
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4380 Nightly builds for vision and audio. Move trigger nightly to action
  .github/actions/trigger-nightly/action.yml
Labels: CLA Signed

#4381 Fix lint for trigger-nightly action
  .github/actions/trigger-nightly/action.yml
Labels: CLA Signed

#4382 Add checkout test-infra step to trigger nightly
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4383 Make nightly commit separate step in trigger-nightly action
  .github/actions/trigger-nightly/action.yml
Labels: CLA Signed

#4384 Refactor code for trigger nightly run
  .github/actions/trigger-nightly/action.yml
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4386 Add Unittests for Build Matrix Generation
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/test_generate_binary_build_matrix.py
Labels: CLA Signed

#4387 Tune timing for nightly builds to 4:30PST
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4360 Option to Generate Matrix without ROCM
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/test_generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#4377 Add SAM to blueberries dashboard
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4390 Add hf_t5_l to blueberries
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4391 Fix the wrong use of Map with Object.keys in getBaseCommitJobs
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
Labels: CLA Signed

#4388 Add torchrec to nightly trigger jobs
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4392 [log classifier] Change inductor model regex
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#4394 Add nightly trigger for pytorch/pytorch
  .github/workflows/trigger_nightly_core.yml
Labels: CLA Signed

#4397 [BE] Add shareable calculate-docker-image GHA
  .github/actions/calculate-docker-image/action.yml
Labels: CLA Signed

#4402 Adds SLI tab for torchci
  torchci/components/NavBar.tsx
  torchci/jest.config.js
  torchci/package.json
  torchci/pages/benchmark/compilers.tsx
  torchci/pages/sli.tsx
  torchci/rockset/metrics/__sql/get_workers_on_period.sql
  torchci/rockset/metrics/__sql/queue_times_historical.sql
  torchci/rockset/metrics/__sql/queue_times_historical_pct.sql
  torchci/rockset/metrics/get_workers_on_period.lambda.json
  torchci/rockset/metrics/queue_times_historical_pct.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/uploadQueryLambda.mjs
  torchci/test/reporter.js
  torchci/yarn.lock
Labels: CLA Signed

#4399 Use shareable calculate-docker-image GHA
  .github/workflows/linux_job.yml
Labels: CLA Signed

#4371 Simplify .gitignore
  .gitignore
Labels: CLA Signed

#4408 Add torchdata to nightly trigger
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#4409 [log classifier] Change inductor model regex again
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#4407 Make compiler names more concise and clear
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4401 Upgrade nightly wheels to ROCm5.6
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
Labels: CLA Signed, module: rocm

#4412 Add an option to init submodules when checking out in Nova jobs
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/test_linux_job.yml
  .github/workflows/test_macos_job.yml
  .github/workflows/test_windows_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#4416 infra: Switch nvidia template to utilize regular cloudwatch config
  terraform-aws-github-runner/modules/runners-instances/launch-template.tf
Labels: CLA Signed

#4423 Add regex support to flaky rules
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
Labels: CLA Signed

#4425 metric 'run.ec2runners.perRunnerType.total' was always being counted twice, fixing it
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
Labels: CLA Signed

#4427 Update readme directory structure
  README.md
Labels: CLA Signed

#4428 Runner provisioning. Add user-data.sh to lambda logs
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4429 Nvidia driver update during runner start
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4430 Nvidia driver update during runner start
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4432 Revert "Revert "Fix gpu pass-though" (#4389)"
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#4431 Add a rule to classify MacOS disk space failure
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#4433 [TorchFix] Filter out files that don't have torch string
  tools/torchfix/torchfix/__main__.py
  tools/torchfix/torchfix/torchfix.py
Labels: CLA Signed

#4435 Added linux.arm64.2xlarge
  .github/scale-config.yml
Labels: CLA Signed

#4434 Add with-rocm param to generate_binary_matrix workflow. Cleanup limit-win-builds param
  .github/workflows/generate_binary_build_matrix.yml
Labels: CLA Signed, module: rocm

#4436 Add nvidia-docker tools installation to worker provisioning
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4437 Add nvidia-docker tools installation to worker provisioning
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4440 Add nvidia-docker tools installation to worker provisioning
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#4441 add force merges kpi
  torchci/package-lock.json
  torchci/package.json
  torchci/pages/kpis.tsx
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/commons/weekly_force_merge_stats.lambda.json
  torchci/rockset/metrics/__sql/force_merge_red_percent.sql
  torchci/rockset/metrics/force_merge_red_percent.lambda.json
  torchci/rockset/prodVersions.json
  torchci/yarn.lock
Labels: CLA Signed

#4443 Fix swapped force merge KPIs
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#4444 improve force merge kpi readability
  torchci/rockset/commons/__sql/weekly_force_merge_stats.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed
