Repository pytorch/test-infra, pull requests merged in 2024-08, with the labels that each got.

#5532 [HUD][ez] Fix disable test button
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#5513 Add basic tooling to validate scale config changes
  .github/scale-config.yml
  .github/scripts/validate_scale_config.py
  .github/workflows/scale_config_validation.yml
Labels: CLA Signed

#5534 ci: Add option for torch dependencies from extra-url
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed, Nova Tooling

#5531 Introduce runner variants to help test changes
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Labels: CLA Signed

#5533 [TD] Update test file ratings: error handling for pulling shas
  tools/torchci/td/get_merge_base_info.py
Labels: CLA Signed

#5541 Runner variants to be aware of the lf. and lf.c. prefixes, to facilitate migrations
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
Labels: CLA Signed

#5539 Uses variants on scale-config and update validate_scale_config to be fully compliant with autoscaler
  .github/scale-config.yml
  .github/scripts/validate_scale_config.py
  .github/workflows/scale_config_validation.yml
Labels: CLA Signed

#5538 Allow full control on `python -m build` command
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#5547 [log classifier] Use llm on for log classifier
  aws/lambda/log-classifier/src/main.rs
Labels: CLA Signed

#5546 Require white space after pytorchbot
  torchci/lib/bot/cliParser.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#5549 New windows runner
  .github/scale-config.yml
Labels: CLA Signed

#5551 [EZ] Enable opting into the old Linux Amazon 2 ami - Pt 2
  .github/scale-config.yml
Labels: CLA Signed

#5555 Bump max runners for linux.24xlarge to 500
  .github/scale-config.yml
Labels: CLA Signed

#5553 [ez][HUD] More flexible regex matching for log line display (mainly affects the disable test button)
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#5561 Remove default for AMIs and add ami_filter_linux_arm64 ami_filter_linux_arm64
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners-instances/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#5557 Add pti env due to kineto xpu enabled
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#5564 Fix SC lint failure after #5557
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#5548 Remove gaurding flag from log classifier
  aws/lambda/log-classifier/src/main.rs
Labels: CLA Signed

#5563 [HUD] Add clickhouse client and some useful functions and an example of a query
  torchci/.env.example
  torchci/clickhouse_queries/commit_jobs_query/params.json
  torchci/clickhouse_queries/commit_jobs_query/query.sql
  torchci/lib/clickhouse.ts
  torchci/lib/fetchCommit.ts
  torchci/package.json
  torchci/pages/api/clickhouse/[queryName].ts
  torchci/yarn.lock
Labels: CLA Signed

#5558 Change default runner's AMI to Amazon 2023 - Part 2
  .github/scale-config.yml
  .github/scripts/validate_scale_config.py
Labels: CLA Signed

#5567 Fix missing ClickHouse SQL queries on Vercel
  torchci/lib/clickhouse.ts
Labels: CLA Signed

#5560 Add a lambda to ingest ServiceLab benchmark results
  .github/workflows/servicelab-ingestor-lambda.yml
  aws/lambda/servicelab-ingestor/Makefile
  aws/lambda/servicelab-ingestor/README.md
  aws/lambda/servicelab-ingestor/lambda_function.py
  aws/lambda/servicelab-ingestor/requirements.txt
Labels: CLA Signed

#5568 tools: Add script to run clickhouse formatter
  .github/scripts/run_clickhouse_format.sh
  .gitignore
Labels: CLA Signed

#5571 [CH migration] Add queued_jobs_by_label
  torchci/clickhouse_queries/queued_jobs_by_label/query.sql
Labels: CLA Signed

#5572 Migrate master_commit_red query and add a ClickHouse toggle on metrics page
  torchci/clickhouse_queries/master_commit_red/params.json
  torchci/clickhouse_queries/master_commit_red/query.sql
  torchci/components/ClickHouseCheckBox.tsx
  torchci/pages/api/clickhouse/[queryName].ts
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5566 [HUD][CH migration] Functioning commit_jobs_query
  torchci/clickhouse_queries/commit_jobs_query/query.sql
  torchci/components/JobLinks.tsx
  torchci/components/LogViewer.tsx
  torchci/lib/clickhouse.ts
  torchci/lib/fetchCommit.ts
Labels: CLA Signed

#5576 Migrate master_commit_red_avg query
  torchci/clickhouse_queries/master_commit_red_avg/params.json
  torchci/clickhouse_queries/master_commit_red_avg/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5578 [disablebot] Exclusion for oncall: pt2 as removable platform label
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#5569 fix: runner-binaries-syncer missing requests module
  terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/package.json
  terraform-aws-github-runner/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/yarn.lock
Labels: CLA Signed

#5580 fix: TFLint error for duplicate output declaration
  terraform-aws-github-runner/outputs.tf
Labels: CLA Signed

#5573 Add ClickHouse version of last_branch_push query
  torchci/clickhouse_queries/last_branch_push/params.json
  torchci/clickhouse_queries/last_branch_push/query.sql
Labels: CLA Signed

#5585 [cherry-pick] Adds kernel-modules-extra and fixes nvida yum repo url for amazon linux 23
  .github/actions/setup-nvidia/action.yml
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5586 Enable certain labels to only be added by a select group of people
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/fixtures/known_labels.json
  torchci/test/labelCommands.test.ts
Labels: CLA Signed

#5579 Upgrade nightly wheels to ROCm6.2
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm, ciflow/rocm

#5589 Remove macos from lintrunner_ci.yml
  .github/workflows/lintrunner_ci.yml
Labels: CLA Signed

#5588 [dashboard] Update export pass rate calculation
  torchci/lib/benchmark/compilerUtils.ts
Labels: CLA Signed

#5590 Add linux.24xlarge.ephemeral runner
  .github/scale-config.yml
Labels: CLA Signed

#5584 [ez][HUD] TTS, workflow load chart: rocm-periodic
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/metrics/__sql/workflow_load.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed, module: rocm, ciflow/rocm

#5592 Add montoring for Linux Foundation fleet rollover
  torchci/pages/metrics.tsx
  torchci/rockset/metrics/__sql/lf_rollover_health.sql
  torchci/rockset/metrics/lf_rollover_health.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5594 Enable setup minimum available runners for scale infra
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/scale-down.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#5544 Remove slow test infra from test-infra
  .github/workflows/update-slow-tests.yml
  stats/README.md
  torchci/rockset/commons/__sql/slow_tests.sql
  torchci/rockset/commons/slow_tests.lambda.json
  torchci/rockset/prodVersions.json
  torchci/scripts/updateSlowTests.mjs
Labels: CLA Signed

#5599 Add mirror of download.pytorch.org to pytorch-test
  s3_management/manage.py
Labels: CLA Signed

#5601 Revert "Add mirror of download.pytorch.org to pytorch-test"
  s3_management/manage.py
Labels: CLA Signed

#5602 [hud][ch] Metrics page scalar panel can toggle ClickHouse
  torchci/components/metrics/panels/ScalarPanel.tsx
Labels: CLA Signed

#5603 [hud][ch] ClickHouse reverts query
  torchci/clickhouse_queries/reverts/params.json
  torchci/clickhouse_queries/reverts/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5604 [ez][hud][ch] Fix numbers being converted to strings
  torchci/lib/clickhouse.ts
Labels: CLA Signed

#5605 [hud][ch] Enable CH for last_branch_push
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5606 [hud][ch] Viable strict lag query
  torchci/clickhouse_queries/strict_lag_sec/params.json
  torchci/clickhouse_queries/strict_lag_sec/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5600 [hud][ch] Use CH queued_jobs_by_label
  torchci/clickhouse_queries/queued_jobs_by_label/params.json
  torchci/clickhouse_queries/queued_jobs_by_label/query.sql
  torchci/components/metrics/panels/TablePanel.tsx
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5609 num_commits to clickhouse
  torchci/clickhouse_queries/num_commits_master/params.json
  torchci/clickhouse_queries/num_commits_master/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed

#5610 Reland "Add mirror of download.pytorch.org to pytorch-test"
  s3_management/manage.py
Labels: CLA Signed

#5597 Allow setting minimum available runners to 0
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#5611 [ez] Exclude check-labels job from flakiness
  torchci/lib/drciUtils.ts
Labels: CLA Signed

#5612 [ez] Add a log classifier rule for check-labels
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#5614 [log classifier] fix https://github.com/pytorch/test-infra/issues/5613
  aws/lambda/log-classifier/src/bedrock.rs
Labels: CLA Signed
