Repository pytorch/test-infra, pull requests merged in 2024-12, with the labels that each got.

#5996 Revert "Set min_runners for linux.2xlarge to 0"
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#5997 Revert "Set min_runners for linux.4xlarge to 0 (#5958)"
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6001 Update generate_binary_build_matrix.py - Restore CUDA 12.1 wheel image
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5994 Update get-workflow-job-id to use relative path to its script
  .github/actions/get-workflow-job-id/action.yml
Labels: CLA Signed

#5950 Make last_successful_jobs query faster
  torchci/clickhouse_queries/last_successful_jobs/query.sql
Labels: CLA Signed

#5998 Revert min-available from AMX runners
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6002 Add windows CUDA 12.6 builds
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#6004 Remove docker build failures from Nightlies HUD page
  tools/rockset_migration/lambdas_backup/nightlies.docker_jobs_red.raw.json
  tools/rockset_migration/lambdas_backup/nightlies.docker_jobs_red_past_day.raw.json
  torchci/clickhouse_queries/docker_jobs_red_past_day/params.json
  torchci/clickhouse_queries/docker_jobs_red_past_day/query.sql
  torchci/pages/nightlies.tsx
  torchci/rockset/nightlies/docker_jobs_red.lambda.json
  torchci/rockset/nightlies/docker_jobs_red_past_day.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#6005 Retry pr_time_benchmarks when it fails
  torchci/lib/bot/retryBot.ts
  torchci/test/retryBot.test.ts
Labels: CLA Signed

#6011 Fix wrong query parameters to TorchInductor summary charts
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
Labels: CLA Signed

#6012 Fix binary upload logic after #5983
  .github/workflows/_binary_upload.yml
Labels: CLA Signed

#6009 [Benchmark]Show all graph for benchmark
  torchci/components/benchmark/compilers/CompilerGraphGroup.tsx
  torchci/components/benchmark/compilers/SuitePicker.tsx
  torchci/lib/benchmark/compliers/CompilerSuites.ts
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#6014 [EZ] Tweak queued_jobs_aggregate query columns
  torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Labels: CLA Signed

#6013 Wait for docker build
  .github/actions/calculate-docker-image/action.yml
Labels: CLA Signed

#6016 Upgrade nightly wheels to ROCm6.2.4 and manylinux2_28
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm, ciflow/rocm

#6006 Display MPS benchmark results in eager mode
  torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
  torchci/components/benchmark/compilers/common.tsx
  torchci/lib/benchmark/compilerUtils.ts
Labels: CLA Signed

#6022 Remove Rockset from backfill script
  .github/workflows/backfill-workflow-job.yml
  torchci/scripts/backfillJobs.mjs
Labels: CLA Signed

#6027 cost dashboard: remove timestamp, add UTC label for tooltip
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6015 Bugfix: Overprovision scaleups on ephemeral instances & extend runner scale up code to enable larger scale ups
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#6008 Add rule to handle missing docs for a new module
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#6023 Add execution time chart on inductor benchmark dashboard
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
  torchci/lib/benchmark/compilerUtils.ts
Labels: CLA Signed

#6039 [EZ] Slightly less ugly metrics page
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6036 [HUD][CH] Move ScalarPanel to only use CH
  torchci/components/metrics/panels/ScalarPanel.tsx
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6034 [HUD][CH] api/hud to only use ClickHouse
  tools/torchci/check_alerts.py
  torchci/lib/fetchHud.ts
  torchci/lib/types.ts
  torchci/lib/useHudData.ts
Labels: CLA Signed

#6035 [HUD][CH] api/.../commit and api/.../pull to only use ClickHouse
  torchci/components/WorkflowDispatcher.tsx
  torchci/lib/fetchCommit.ts
  torchci/lib/fetchPR.ts
  torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
  torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
  torchci/pages/api/[repoOwner]/[repoName]/commit/[sha].ts
  torchci/pages/api/[repoOwner]/[repoName]/pull/[prNumber].ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#6030 [HUD] Fix docs push panel when using CH, ttrs kpi to use CH
  torchci/clickhouse_queries/last_successful_jobs/query.sql
  torchci/components/metrics/panels/TimeSeriesPanel.tsx
  torchci/pages/kpis.tsx
Labels: CLA Signed

#6037 [HUD][CH] Some assorted components on metrics page to always use ClickHouse
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6041 [EZ] Metrics page bugfix
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6031 [HUD] Remove test insights page
  torchci/components/JobLinks.tsx
  torchci/components/TestInsights.tsx
  torchci/components/WorkflowBox.tsx
  torchci/pages/test/insights.tsx
Labels: CLA Signed

#6029 Move Validation Framework workflows to test-infra
  .github/scripts/validate_binaries.sh
  .github/scripts/validate_pipy.sh
  .github/scripts/validate_poetry.sh
  .github/scripts/validate_test_ops.sh
  .github/scripts/xpu_env_helper.bat
  .github/workflows/generate_binary_build_matrix.yml
  .github/workflows/generate_docker_release_matrix.yml
  .github/workflows/validate-aarch64-linux-binaries.yml
  .github/workflows/validate-binaries.yml
  .github/workflows/validate-docker-images.yml
  .github/workflows/validate-linux-binaries.yml
  .github/workflows/validate-macos-arm64-binaries.yml
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-nightly-pypi-wheel-binary-size.yml
  .github/workflows/validate-release-binaries.yml
  .github/workflows/validate-windows-binaries.yml
Labels: CLA Signed

#6047 [EZ] Add XPU workflows opt in for trunk
  torchci/components/WorkflowDispatcher.tsx
Labels: CLA Signed

#6049 Move current release candidate to 2.6.0
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6050 Move current release candidate to 2.6.0
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6051 fix date displaying on link copying
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6055 allow to group by gpu/non-gpu
  torchci/clickhouse_queries/cost_job_per_gpu/params.json
  torchci/clickhouse_queries/cost_job_per_gpu/query.sql
  torchci/clickhouse_queries/duration_job_per_gpu/params.json
  torchci/clickhouse_queries/duration_job_per_gpu/query.sql
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6054 cost page: fix for when there are no parameters set, default to 7 days
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6052 add a permalink button to copy cost url with params / daterange
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6058 Adds swap space for ALI runners and report to ci and metrics if it is used
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6057 Migrate LLM dashboards to v3
  torchci/clickhouse_queries/oss_ci_benchmark_branches/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_names/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
  torchci/components/benchmark/llms/common.tsx
  torchci/lib/benchmark/llmUtils.ts
  torchci/pages/benchmark/llms.tsx
Labels: CLA Signed

#6061 mandate IMDSv2 on all new ec2 runners
  terraform-aws-github-runner/modules/runners-instances/launch-template.tf
Labels: CLA Signed

#6066 Clean up existing swapfile before trying to allocate a new one
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6068 Fix a bug when swapfile doesn't exist
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6067 [release-only] Pin Docker images for release 2.6
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed

#6070 Enable rocm support on 3.13 python
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#6062 add cu126 torchvision and torchaudio aarch64 build
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm

#6071 Update pep503_whl_redirect to accomodate for rocm maj.min.patch version
  aws/websites/download.pytorch.org/pep503_whl_redirect.js
Labels: CLA Signed, module: rocm, ciflow/rocm

#6075 [cherry-pick] add cu126 torchvision and torchaudio aarch64 build
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6076 [cherry-pick] Enable rocm support on 3.13 python
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#6072 Fix logic in validate aarch64 and xpu linux binaries
  .github/workflows/validate-aarch64-linux-binaries.yml
  .github/workflows/validate-linux-binaries.yml
  .github/workflows/validate-nightly-binaries.yml
Labels: CLA Signed

#6078 Use devtoolset x11-abi for XPU builds validations.
  .github/scripts/validate_binaries.sh
Labels: CLA Signed

#6064 Add Packer Build job for Windows AMI
  .github/workflows/build-windows-ami.yml
Labels: CLA Signed

#6074 allow cost dashboard to be grouped by repo
  torchci/clickhouse_queries/cost_job_per_repo/params.json
  torchci/clickhouse_queries/cost_job_per_repo/query.sql
  torchci/clickhouse_queries/duration_job_per_repo/params.json
  torchci/clickhouse_queries/duration_job_per_repo/query.sql
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6080 Use rocm images for rocm validations and set devtoolset correctly similar to xpu
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-linux-binaries.yml
Labels: CLA Signed, module: rocm, ciflow/rocm

#6083 Use latest numpy 2+ for validaiton of wheels
  .github/scripts/validate_binaries.sh
Labels: CLA Signed

#6087 Add TorchAO LLM benchmark dashboard
  torchci/clickhouse_queries/oss_ci_benchmark_branches/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_llms/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_names/params.json
  torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
  torchci/components/NavBar.tsx
  torchci/components/benchmark/llms/ModelGraphPanel.tsx
  torchci/components/benchmark/llms/SummaryPanel.tsx
  torchci/components/benchmark/llms/common.tsx
  torchci/lib/benchmark/llmUtils.ts
  torchci/pages/benchmark/llms.tsx
Labels: CLA Signed

#6081 Delete td_rockset_analysis script
  tools/torchci/td/td_rockset_analysis.py
Labels: CLA Signed

#6084 [HUD] Delete correlation matrix page and the script used to generate it
  tools/torchci/compute_correlation.py
  torchci/lib/correlation_matrix.json
  torchci/pages/correlation.tsx
Labels: CLA Signed

#6088 [BE] [PyTorchBot] More understandable error message when labels cannot be added
  torchci/lib/bot/ciflowPushTrigger.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/labelCommands.test.ts
Labels: CLA Signed

#6069 [HUD] Reduce number of clicks for expanding grouping
  torchci/components/GroupHudTableHeaders.tsx
Labels: CLA Signed

#6073 Convert torchbench_list_userbenchmarks to CH
  torchci/clickhouse_queries/torchbench_list_userbenchmarks/query.sql
Labels: CLA Signed

#6090 Nightlies page use clickhouse, deprecate rockset
  torchci/clickhouse_queries/nightly_jobs_red/params.json
  torchci/clickhouse_queries/nightly_jobs_red/query.sql
  torchci/clickhouse_queries/nightly_jobs_red_by_name/query.sql
  torchci/clickhouse_queries/nightly_jobs_red_by_platform/params.json
  torchci/clickhouse_queries/nightly_jobs_red_by_platform/query.sql
  torchci/clickhouse_queries/nightly_jobs_red_past_day/query.sql
  torchci/clickhouse_queries/validation_jobs_red_past_day/query.sql
  torchci/pages/nightlies.tsx
Labels: CLA Signed

#6094 [HUD] Show the unstable button even if the job is successful
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#6095 Compute GPU runner usage stats
  tools/fleet_analysis/runner_usage_stats.ipynb
Labels: CLA Signed

#6092 [HUD][CH] Update README with ClickHouse information
  torchci/.env.example
  torchci/README.md
Labels: CLA Signed

#6098 [HUD] Update README with info about getting access to Vercel
  torchci/.env.example
  torchci/README.md
Labels: CLA Signed

#6099 Don't do libtorch pre-cxx11-abi for ROCm
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#6103 Remove rocm pre-cxx11 abi
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#6059 Add release scripts and workflow validate-repackaged-size
  .github/workflows/validate-repackaged-binary-sizes.yml
  release/README.md
  release/promote.sh
  release/promote/common_utils.sh
  release/promote/conda_to_conda.sh
  release/promote/prep_binary_for_pypi.sh
  release/promote/s3_to_s3.sh
  release/promote/wheel_to_pypi.sh
  release/pypi/prep_binary_for_pypi.sh
  release/pypi/promote_pypi_to_production.sh
  release/pypi/promote_pypi_to_staging.sh
  release/pypi/upload_pypi_to_staging.sh
  release/release_versions.sh
  release/restore-backup.sh
Labels: CLA Signed

#6108 Handle closed pull requests and empty pull requests with no commit
  torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
  torchci/lib/fetchPR.ts
  torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#6111 Move analytics scripts from builder
  tools/analytics/cubinsizes.py
  tools/analytics/download_count_wheels.py
  tools/analytics/duplicates_analyze.py
  tools/analytics/github_analyze.py
  tools/analytics/s3_test_stats_analyze.py
  tools/analytics/validate_binaries.py
  tools/analytics/validate_pypi_staging.py
Labels: CLA Signed

#6101 Bring back TorchBench AO dashboard
  torchci/clickhouse_queries/torchao_query/params.json
  torchci/clickhouse_queries/torchao_query/query.sql
  torchci/clickhouse_queries/torchao_query_branches/params.json
  torchci/clickhouse_queries/torchao_query_branches/query.sql
  torchci/components/benchmark/compilers/CompilerGraphGroup.tsx
  torchci/components/benchmark/compilers/ModelGraphPanel.tsx
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
  torchci/components/benchmark/torchao/common.tsx
  torchci/lib/benchmark/aoUtils.ts
  torchci/lib/types.ts
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
  torchci/pages/benchmark/compilers.tsx
  torchci/pages/benchmark/torchao.tsx
Labels: CLA Signed

#6110 Add support for benchmark configs on ExecuTorch dashboard
  torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
  torchci/pages/benchmark/llms.tsx
Labels: CLA Signed

#6118 Add speedup metric for TorchAO
  torchci/components/benchmark/llms/ModelGraphPanel.tsx
  torchci/components/benchmark/llms/SummaryPanel.tsx
  torchci/components/benchmark/llms/common.tsx
  torchci/lib/benchmark/aoUtils.ts
  torchci/lib/benchmark/llmUtils.ts
  torchci/pages/benchmark/llms.tsx
Labels: CLA Signed

#6119 Add TorchAO aggregated geomean speedup metric
  torchci/components/benchmark/llms/ModelGraphPanel.tsx
  torchci/components/benchmark/llms/SummaryPanel.tsx
  torchci/components/benchmark/llms/common.tsx
  torchci/lib/benchmark/llmUtils.ts
  torchci/pages/benchmark/llms.tsx
Labels: CLA Signed

#6122 Convert torchbench_userbenchmark_query_metrics to CH
  torchci/clickhouse_queries/torchbench_userbenchmark_query_metrics/query.sql
Labels: CLA Signed
