Repository pytorch/test-infra, pull requests merged in 2024-07, with the labels that each got.

#5386 Add manual kernel headers installation to unblock user-data execution
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5389 Fixing package name kernel-devel-uname-r on user-data.sh + fix shell expansion
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5390 [Reland] "Add linux.g6.4xlarge.experimental.nvidia.gpu runner type"
  .github/scale-config.yml
Labels: CLA Signed

#5347 [HUD] Flaky tests page: Require more specific search, include rerun disabled tests jobs
  torchci/pages/api/flaky-tests/flakytest.ts
  torchci/pages/flakytest.tsx
Labels: CLA Signed

#5353 [Windows AMI] Bump minconda to 24.4.0
  aws/ami/windows/scripts/Installers/Initialize-Python3.ps1
  aws/ami/windows/scripts/Installers/Install-Choco-GenerateProfile.ps1
  aws/ami/windows/scripts/Installers/Install-Miniconda3.ps1
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#5387 [aarch64] add cuda aarch64 torchvision and torchaudio
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5397 Fallback to Node16 while upgrading runner to AmazonLinux2023
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
Labels: CLA Signed

#5399 Userdata send cloudwatch metrics to setup alerts on failures
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5401 Add pytorch_triton_xpu to list of allowed packages
  s3_management/manage.py
Labels: CLA Signed

#5403 Add xpu subdir for s3 management
  s3_management/manage.py
Labels: CLA Signed

#5398 Rockset migration - move upload for queue_times_historical from rockset to s3
  torchci/rockset/metrics/__sql/queued_jobs_by_label.sql
  torchci/rockset/prodVersions.json
  torchci/scripts/updateQueueTimes.mjs
Labels: CLA Signed

#5411 Rockset migration - update queue times - set aws permissions in workflow
  .github/workflows/update-queue-times.yml
Labels: CLA Signed

#5412 Rockset migration - update queue times- explicitly use the new time field instead of _event_time and fix env variables in update queue times workflow
  .github/workflows/update-queue-times.yml
  torchci/rockset/metrics/__sql/queue_times_historical.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5395 [ez][HUD] Main page permalink to use sha from page one
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#5417 [queue times] Use correct env vars
  torchci/scripts/updateQueueTimes.mjs
Labels: CLA Signed

#5406 Adds support to experiment with AMI runner-by-runner
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-issues.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/policies/lambda-scale-up.json
Labels: CLA Signed

#5418 [queue times] Actually use correct env vars
  .github/workflows/update-queue-times.yml
  torchci/scripts/updateQueueTimes.mjs
Labels: CLA Signed

#5377 [RS migration] merge_bases generation script to upload to s3 instead of rockset
  .github/workflows/update_test_file_ratings.yml
  tools/torchci/rockset_utils.py
  tools/torchci/td/get_merge_base_info.py
Labels: CLA Signed

#5375 [RS migration][drci] upload merge bases to s3, fix changed files query
  torchci/lib/s3.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#5410 [Rockset migration] Switch to oss_ci_benchmark_v2 powered by dynamoDB
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_llms.sql
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_names.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5415 [Rockset migration] Switch to torch_dynamo_perf_stats_v2 powered by dynamoDB
  torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql
  torchci/rockset/inductor/__sql/compilers_benchmark_performance_branches.sql
  torchci/rockset/inductor/compilers_benchmark_performance_branches.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5413 Update aws packages for rust
  aws/lambda/log-classifier/Cargo.lock
  aws/lambda/log-classifier/Cargo.toml
  aws/lambda/log-classifier/src/network.rs
Labels: CLA Signed

#5414 [hud] Add llm logic to log classifier
  .lintrunner.toml
  aws/lambda/log-classifier/Cargo.lock
  aws/lambda/log-classifier/Cargo.toml
  aws/lambda/log-classifier/fixtures/error_log1.txt
  aws/lambda/log-classifier/src/bedrock.rs
  aws/lambda/log-classifier/src/bedrock/prompts.rs
  aws/lambda/log-classifier/src/lib.rs
  aws/lambda/log-classifier/src/main.rs
  aws/lambda/log-classifier/src/snapshots/log_classifier__test__create_log_snippet.snap
Labels: CLA Signed

#5400 Pin AMZN2023 images for non-gpu instances, starting amzn2023 migration
  .github/scale-config.yml
Labels: CLA Signed

#5421 Improves visibility for AMI experiments
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#5422 Increase max runners available for linux.4xlarge.nvidia.gpu and linux.g5.4xlarge.nvidia.gpu
  .github/scale-config.yml
Labels: CLA Signed

#5424 Move user-data and daemon monitoring to a separate CW namespace
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5420 [log-classifier] Improve validation logic to check lines in log specifically
  aws/lambda/log-classifier/src/bedrock.rs
  aws/lambda/log-classifier/src/main.rs
  aws/lambda/log-classifier/src/snapshots/log_classifier__bedrock__test__create_log_snippet.snap
Labels: CLA Signed

#5426 Run nvidia-persistenced to avoid timeout error when initializing Docker containers
  .github/actions/setup-nvidia/action.yml
  aws/lambda/log-classifier/src/bedrock.rs
Labels: CLA Signed

#5427 Enable experiment with AMZN 2023 for linux.4xlarge.nvidia.gpu
  .github/scale-config.yml
Labels: CLA Signed

#5428 Adds metada options on launch instance templates to set idsv1 optional
  terraform-aws-github-runner/modules/runners-instances/launch-template.tf
Labels: CLA Signed

#5430 Stop AMZN2023 experiment
  .github/scale-config.yml
Labels: CLA Signed

#5396 [HUD] Main page: better grouping in full view for jobs that are unstable and mem leak check/rerun disabled tests
  torchci/lib/JobClassifierUtil.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#5432 [HUD] Slightly improved repro copy paste for failure, do not require authentication to see copy paste link
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#5409 [BE] Apply lintrunner on rockset_queries.py
  tools/rockset_migration/rockset_queries.ipynb
  tools/rockset_migration/rockset_queries.py
Labels: CLA Signed

#5480 Remove workaround to install kernel-devel
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5484 Fix typo preventing auto-creation of release labels
  .github/workflows/lambda-release-tag-runners.yml
Labels: CLA Signed

#5457 [flakybot] Fix sql query
  torchci/rockset/commons/__sql/flaky_tests.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5483 Fix alert for no new flaky tests spamming
  tools/torchci/check_alerts.py
  tools/torchci/tests/test_check_alerts.py
Labels: CLA Signed

#5485 Emit Runner info at the start of every job on self hosted linux runners
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
Labels: CLA Signed

#5487 Add new runner types for the amazon 2023 ami
  .github/scale-config.yml
Labels: CLA Signed

#5488 [flakybot] Increase threshold for number of jobs needed to make a flaky issue to 3
  torchci/pages/api/flaky-tests/disable.ts
Labels: CLA Signed

#5456 Add errors="backslashreplace" to run_with_env_secrets.py
  .github/scripts/run_with_env_secrets.py
Labels: CLA Signed

#5494 Release 2.4 stable version bump
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#5496 Fix linux.arm64 GPU validations
  .github/workflows/linux_job.yml
Labels: CLA Signed

#5486 [flakybot] Instructions to re-enable test in validation comment
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#5489 Add XPU to binary build generation
  .github/workflows/build_wheels_linux.yml
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/test_generate_binary_build_matrix.py
Labels: CLA Signed

#5498 Add new type of ephemeral runners linux.9xlarge to be used for docker builds
  .github/scale-config.yml
Labels: CLA Signed

#5425 [log classifier] Add functionality to find multiple snippets
  aws/lambda/log-classifier/Cargo.lock
  aws/lambda/log-classifier/Cargo.toml
  aws/lambda/log-classifier/fixtures/error_log_multiple_matches.txt
  aws/lambda/log-classifier/src/bedrock.rs
  aws/lambda/log-classifier/src/engine.rs
  aws/lambda/log-classifier/src/snapshots/log_classifier__bedrock__test__create_log_snippet.snap
  aws/lambda/log-classifier/src/snapshots/log_classifier__engine__test__get_snippets_on_log.snap
  aws/lambda/log-classifier/src/snapshots/log_classifier__engine__test__get_snippets_on_log_with_multiple_matches.snap
Labels: CLA Signed

#5499 [flakybot] Temporarily ignore sdpa issues, there are too many
  torchci/pages/api/flaky-tests/disable.ts
Labels: CLA Signed

#5501 Small improvements designed to increase the resiliency of ephemeral instances
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#5497 Add ARM metal instances for perf measurement
  .github/scale-config.yml
Labels: CLA Signed

#5433 [HUD] Add button for copying common revert message info/links
  torchci/components/CopyLink.tsx
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#5479 On ScaleDown remove old/stale SSM parameters
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Labels: CLA Signed

#5503 Fix bug with emitting logs from runners
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
Labels: CLA Signed

#5491 Add the list of devices on PT2 inductor perf dashboard
  torchci/components/benchmark/ModeAndDTypePicker.tsx
  torchci/components/benchmark/compilers/ModelPanel.tsx
  torchci/components/benchmark/compilers/SummaryPanel.tsx
  torchci/components/benchmark/compilers/common.tsx
  torchci/components/benchmark/torchao/common.tsx
  torchci/lib/benchmark/compilerUtils.ts
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
  torchci/pages/benchmark/compilers.tsx
  torchci/pages/benchmark/torchao.tsx
Labels: CLA Signed

#5505 Add cuda (a10g) device to TorchInductor dashboard
  torchci/components/benchmark/compilers/common.tsx
Labels: CLA Signed

#5507 Provision Graviton instances with ARM64 AL2023
  .github/scale-config.yml
Labels: CLA Signed

#5508 Remove py312 and rocm restriction
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm, ciflow/rocm

#5509 Cherry Pick of #5508
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed

#5502 [ez][HUD] TTS, workflow load chart: add rocm, rocm periodic, inductor periodic
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/rockset/metrics/__sql/workflow_load.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed, module: rocm, ciflow/rocm

#5510 [HUD] Fix repro copy paste
  torchci/components/JobLinks.tsx
  torchci/components/ReproductionCommand.tsx
Labels: CLA Signed

#5511 Make scale-config.yml self-consistent
  .github/scale-config.yml
Labels: CLA Signed

#5514 Increase max runners available for m4.10xlarge
  .github/scale-config.yml
Labels: CLA Signed

#5517 Drop python 3.8 support for Nova workflows
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#5516 Adds replace_runners_prefix_submit_pr.py to quickly help test new runners in partner repos
  tools/self-hosted-runner-utils/replace_runners_prefix_submit_pr.py
Labels: CLA Signed

#5525 Differentiate between cuda (a100) and cuda (a10g) commits on perf dashboard
  torchci/rockset/inductor/__sql/compilers_benchmark_performance.sql
  torchci/rockset/inductor/__sql/compilers_benchmark_performance_branches.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5527 Apply $CONDA_ENV fix for smoke tests
  .github/workflows/build_conda_linux.yml
Labels: CLA Signed

#5530 Added option to pass extra args to python wheel build command
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed
