Repository pytorch/test-infra, pull requests merged in 2024-03, with the labels that each got.

#4976 Add mkl packages to allow-list
  s3_management/manage.py
Labels: CLA Signed

#4973 Add a Nova workflow to run iOS test on AWS Device Farm
  .github/workflows/mobile_job.yml
  .github/workflows/test_mobile_job.yml
  tools/device-farm-runner/requirements.txt
  tools/device-farm-runner/run_on_aws_devicefarm.py
Labels: CLA Signed

#4978 Add cudnn to updatable_dependencies
  s3_management/update_dependencies.py
Labels: CLA Signed

#4979 [ez][HUD] Sort artifacts
  torchci/lib/fetchS3Links.ts
Labels: CLA Signed

#4985 Cleanup ARC configs
  .github/arc-runner-config.yaml
Labels: CLA Signed

#4989 Removed macos-m1-12 label
  .github/actionlint.yaml
Labels: CLA Signed

#4983 Add sam_fast to dashboard
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4993 Add sam_fast to dashboard (#4983)
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4991 Forces docker login on calculate-docker-image and pull-docker-image
  .github/actions/calculate-docker-image/action.yml
  .github/actions/pull-docker-image/action.yml
Labels: CLA Signed

#4999 Revert "Forces docker login on calculate-docker-image and pull-docker-image"
  .github/actions/calculate-docker-image/action.yml
  .github/actions/pull-docker-image/action.yml
Labels: CLA Signed

#5000 Increase number of runners for linux.2xlarge
  .github/arc-runner-config.yaml
Labels: CLA Signed

#5002 Tuning resources to reflect what is on scale-config.yml
  .github/arc-runner-config.yaml
Labels: CLA Signed

#5001 Reland "Forces docker login on calculate-docker-image and pull-docker-image" (#4999)"
  .github/actions/calculate-docker-image/action.yml
  .github/actions/pull-docker-image/action.yml
Labels: CLA Signed

#4995 [bots] Move labeler action to test-infra
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/utils.ts
  torchci/package.json
  torchci/test/autoLabelBot.test.ts
  torchci/yarn.lock
Labels: CLA Signed

#4998 Fix Dr.CI flaky FP when GH fails to dispatch the workflow
  torchci/lib/drciUtils.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#5003 Add nightly trigger for executorch
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#5004 [drci] Optimize sql query for recent workflow jobs
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5006 Trigger executorch nightly off viable/strict
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#5008 Bump PT candidate version to 2.3.0 now that RC1 is out
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5021 Remove ROCm 5.6 and add ROCm 6.0
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#5011 Publish ExecuTorch wheel on download.pytorch.org
  s3_management/manage.py
Labels: CLA Signed

#5023 [bots] Do not add trunk label if codev but no workflow running permissions
  torchci/lib/bot/autoLabelBot.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed

#5024 [bots][ez] Remove unused acceptBot file
  torchci/lib/bot/acceptBot.ts
  torchci/lib/bot/index.ts
  torchci/test/acceptBot.test.ts
Labels: CLA Signed

#5025 [bots] Do not add ciflow/trunk label if the author does not have permissions
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/lib/bot/utils.ts
  torchci/test/common.ts
  torchci/test/labelCommands.test.ts
  torchci/test/mergeCommands.test.ts
  torchci/test/utils.ts
Labels: CLA Signed

#5027 [bots] Bot to comment wiki link on codev PRs with no write permissions
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/codevNoWritePermBot.ts
  torchci/lib/bot/index.ts
  torchci/test/autoLabelBot.test.ts
  torchci/test/codevNoWritePermBot.test.ts
  torchci/test/utils.ts
Labels: CLA Signed

#5031 Update generate_binary_build_matrix.py for release 2.2.2
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5026 [ez][HUD] Optimize query for TTRS, previous commits on PR
  torchci/rockset/commons/__sql/pr_commits.sql
  torchci/rockset/prodVersions.json
  torchci/rockset/pytorch_dev_infra_kpis/__sql/ttrs_percentiles.sql
Labels: CLA Signed

#5033 [lambdas][github-status-test] Select random token
  aws/lambda/github-status-test/lambda_function.py
Labels: CLA Signed

#5034 Do not set the merge base date to the mock value of 0
  torchci/lib/drciUtils.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#5036 [BE] Add message about skip ci decorators
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#5037 [ez] Support trigger ROCm workflow in trunk
  torchci/components/WorkflowDispatcher.tsx
Labels: CLA Signed, module: rocm, ciflow/rocm

#5039 [ez] uploadQueryLambdas - Allow description for lambdas to be different types
  torchci/scripts/uploadQueryLambda.mjs
Labels: CLA Signed

#5038 [drci] Remove failed workflows if there is a succeeding one
  torchci/lib/types.ts
  torchci/pages/api/drci/drci.ts
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/prodVersions.json
  torchci/test/drci.test.ts
Labels: CLA Signed

#5045 Advance release matrix ahead of 2.2.2
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#5047 [bots] Bot to rerun workflows that fail due to weird infra error
  torchci/lib/bot/index.ts
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5042 [ez][HUD] Move joins around to make queries faster
  torchci/rockset/metrics/__sql/master_commit_red.sql
  torchci/rockset/metrics/__sql/master_commit_red_avg.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5048 [ez][log classifier] More specific bazel build failure rule
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#5052 [bots] Add logging to rerunGithubInfraErrorWorkflow
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5051 [torchci] Aggregate dependabot changes into one PR
  tools/torchci/requirements.txt
  torchci/package-lock.json
  torchci/package.json
  torchci/yarn.lock
Labels: CLA Signed

#5053 [bots] Continuation of #5052 ( adding logging )
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed
