Repository pytorch/test-infra, pull requests merged in 2024-02, with the labels that each got.

#4917 Fix indexes for mixed upper/lower case names
  s3_management/manage.py
Labels: CLA Signed

#4921 test
  .github/workflows/trigger_nightly_core.yml
Labels: CLA Signed

#4918 Replace AWS credentials on upload-tutorials-stats with OIDC
  .github/workflows/upload-tutorials-stats.yml
Labels: CLA Signed

#4919 Add log classifier rule for ET model tests
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#4922 Update lambda deployment workflow with OIDC
  .github/workflows/github-status-test-lambda.yml
  .github/workflows/log-classifier-lambda.yml
  .github/workflows/opensearch-gha-jobs-lambda.yml
Labels: CLA Signed

#4923 Clean up non-existing github_status_webhook_handler lambda workflow
  .github/workflows/lambda_github_status_webhook_handler.yml
Labels: CLA Signed

#4929 Update ghstack-mergeability-check flakiness rules
  stats/flaky-rules.json
Labels: CLA Signed

#4758 torchci: Add parser / handler for cherry picks
  torchci/lib/bot/Constants.ts
  torchci/lib/bot/cliParser.ts
  torchci/lib/bot/pytorchBotHandler.ts
Labels: CLA Signed

#4931 Add a runner with 8 GPUs for Distributed team
  .github/scale-config.yml
Labels: CLA Signed

#4924 Fix path for dashboard link page
  torchci/pages/benchmark/compilers.tsx
Labels: CLA Signed

#4935 Fix test insight page
  .github/workflows/usage-log-aggregator-lambda.yml
  aws/lambda/usage-log-aggregator/Makefile
  aws/lambda/usage-log-aggregator/lambda_function.py
  aws/lambda/usage-log-aggregator/test_lambda_function.py
  torchci/components/TestInsights.tsx
  torchci/pages/test/insights.tsx
Labels: CLA Signed

#4936 Fix vision windows conda nightly. Remove pinned conda version
  .github/workflows/build_conda_windows.yml
Labels: CLA Signed

#4937 Specify the docker mode for ARC on arc-runner-config.yaml
  .github/arc-runner-config.yaml
Labels: CLA Signed

#4939 advance rocm to 5.7 and 6.0 in nightly
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#4940 Add tool/__init__.py
  tools/__init__.py
Labels: CLA Signed

#4943 [CI] Run `tests.yml` more
  .github/workflows/tests.yml
Labels: CLA Signed

#4942 Fix `test_generate_binary_build_matrix`
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed

#4941 [HUD][ez] Double click log viewer in job tooltip (hud main page) no longer opens gh job
  torchci/components/LogViewer.tsx
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#4632 Copyable Reproduction Fix
  torchci/components/JobLinks.tsx
Labels: CLA Signed

#4944 Specific PYTORCH_VERSION when building RC for test channel #
  .github/actions/set-channel/action.yml
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#4945 Cherry pick a bunch of OIDC changes for 2.2.1 release
  .github/actions/setup-binary-builds/action.yml
  .github/actions/setup-binary-upload/action.yml
  .github/workflows/_binary_conda_upload.yml
  .github/workflows/_binary_upload.yml
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  .github/workflows/test_build_conda_linux_with_cuda.yml
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_conda_windows_with_cuda.yml
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_linux_aarch64_without_cuda.yml
  .github/workflows/test_build_wheels_linux_with_cuda.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows_with_cuda.yml
  .github/workflows/test_build_wheels_windows_without_cuda.yml
Labels: CLA Signed

#4946 Update generate_binary_build_matrix for release 2.2.1
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#4745 Enable footer for the DataGrid widget to enable paging
  torchci/components/metrics/panels/TablePanel.tsx
  torchci/pages/torchbench/userbenchmark.tsx
Labels: CLA Signed

#4949 Create Dr.CI comment if it doesn't exist
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#4954 Bump current candidate version to 2.2.1
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed

#4955 Keep the behavior of DataGrid table to hide the footer by default
  torchci/components/metrics/panels/TablePanel.tsx
  torchci/pages/torchbench/userbenchmark.tsx
Labels: CLA Signed

#4956 Hide suppressed bc linter failure on Dr.CI (and mergebot)
  torchci/lib/drciUtils.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drciBot.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#4958 Always run binary upload
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#4962 Always run binary upload
  .github/workflows/build_conda_linux.yml
  .github/workflows/build_conda_macos.yml
  .github/workflows/build_conda_windows.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#4963 Fix hasS3Log and disable similarity search on non-PyTorch repos
  torchci/lib/jobUtils.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#4964 Release 2.2.1 update scripts
  tools/scripts/generate_binary_build_matrix.py
  tools/scripts/generate_release_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#4966 [alerts] Close issue if there are too many comments
  tools/torchci/check_alerts.py
Labels: CLA Signed

#4971 [lambda] Use requests for github-status-test
  aws/lambda/github-status-test/lambda_function.py
  aws/lambda/github-status-test/requirements.txt
Labels: CLA Signed

#4972 Follow up to #4971
  aws/lambda/github-status-test/lambda_function.py
Labels: CLA Signed

#4948 Use index-url for all test steps
  .github/workflows/test-export-matrix-variables.yml
  .github/workflows/test_linux_job.yml
  .github/workflows/test_macos_job.yml
  .github/workflows/test_windows_job.yml
  tools/pkg-helpers/pytorch_pkg_helpers/wheel.py
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed
