Repository pytorch/test-infra, pull requests merged in 2024-04, with the labels that each got.

#5041 Use APPIUM_NODE_TEST_SPEC custom test spec to support test discovery
  .github/workflows/mobile_job.yml
  .github/workflows/test_mobile_job.yml
  tools/device-farm-runner/run_on_aws_devicefarm.py
Labels: CLA Signed

#5057 Add ``torchtune`` to nightly trigger
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#5058 Add ``torchtune`` to package allow list
  s3_management/manage.py
Labels: CLA Signed

#5059 [bots] Rerun github infra failure bot - delete tag on workflow completion
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5060 [bots] Fix #5059
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5061 [bots] Follow up for #5060
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5064 [bots] Fix after #5061
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5065 Add docker release matrix workflow
  .github/workflows/generate_docker_release_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/scripts/generate_docker_release_matrix.py
Labels: CLA Signed

#5068 Remove outdated comments
  .github/workflows/update-drci-comments.yml
  torchci/lib/drciUtils.ts
Labels: CLA Signed

#5067 [bots] Local testing wiki link
  torchci/README.md
Labels: CLA Signed

#5055 [TD][bots] Auto add TD rollout label
  torchci/lib/bot/autoLabelBot.ts
  torchci/test/autoLabelBot.test.ts
  torchci/test/utils.ts
Labels: CLA Signed

#5071 Utilize Python build package instead of setup.py
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#5078 Remove torchtext tests from CI
  .github/workflows/test_build_conda_linux_with_cuda.yml
  .github/workflows/test_build_conda_linux_without_cuda.yml
  .github/workflows/test_build_conda_m1.yml
  .github/workflows/test_build_conda_macos.yml
  .github/workflows/test_build_conda_windows_with_cuda.yml
  .github/workflows/test_build_conda_windows_without_cuda.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  .github/workflows/test_build_wheels_m1.yml
  .github/workflows/test_build_wheels_macos.yml
  .github/workflows/test_build_wheels_windows_without_cuda.yml
Labels: CLA Signed

#5076 Allow old packages to default to setup.py-based build
  .github/workflows/build_wheels_linux.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
Labels: CLA Signed

#5081 Add docker image to docker release matrix
  tools/scripts/generate_binary_build_matrix.py
  tools/scripts/generate_docker_release_matrix.py
Labels: CLA Signed

#5084 tools: Add ability to build a python only package
  .github/workflows/generate_binary_build_matrix.yml
  .github/workflows/test_build_wheels_linux_without_cuda.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/test_generate_binary_build_matrix.py
Labels: CLA Signed

#5083 Adds node type compute-amd64-avx512, runner type linux.2xlarge.avx512 and improve node selection for compute-amd64
  .github/arc-node-config.yaml
  .github/arc-runner-config.yaml
Labels: CLA Signed

#5086 .github: Fix blank repository variable
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#5087 Windows AMI - add cuda 12.4
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#5088 Add rules for Python ValueError and TypeError
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#5070 This is a test for whether or not probot is stateful
  torchci/lib/bot/index.ts
  torchci/lib/bot/statefulBot.ts
Labels: CLA Signed

#5092 Support the upload of custom artifacts from artifacts-to-be-uploaded folder
  .github/workflows/linux_job.yml
  .github/workflows/macos_job.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#5082 [bots] Github infra error frequency decreased, delete bot
  torchci/lib/bot/index.ts
  torchci/lib/bot/rerunGithubInfraErrorWorkflow.ts
Labels: CLA Signed

#5077 Add Android support to mobile job workflow
  .github/workflows/mobile_job.yml
  .github/workflows/test_mobile_job.yml
  tools/device-farm-runner/run_on_aws_devicefarm.py
Labels: CLA Signed

#5095 Add `submodule` input for build_wheels_*.yaml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#5096 cherry-pick: Add `submodule` input for build_wheels_*.yaml (#5095)
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#5100 [Refactor] Extract out a utility function: getFilesChangedByPr
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/index.ts
  torchci/lib/bot/utils.ts
Labels: CLA Signed

#5098 [ez][bots] Remove stateful check bot from #5070
  torchci/lib/bot/index.ts
  torchci/lib/bot/statefulBot.ts
Labels: CLA Signed

#5102 Use ON_DEMAND instances for ARC nodes config to avoid disruptions
  .github/arc-node-config.yaml
Labels: CLA Signed

#5108 cherry-pick: Add inputs.delocate-wheel to build_wheels_macos.yaml
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#5107 Add inputs.delocate-wheel to build_wheels_macos.yaml
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#5110 Allows roles in account 391835788720 to assume gha-ci node role
  terraform-aws-github-runner/modules/runners-instances/policies/instance-role-trust-policy.json
Labels: CLA Signed

#5109 Update ``update_dependencies.py`` script
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#5106 Exclude lint and backwards_compat from Dr.CI flaky check
  torchci/lib/drciUtils.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#5118 Release 2.3 bump stable version, bump rocm version for release. Update test assets
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/update_test_assets.sh
Labels: CLA Signed, module: rocm, ciflow/rocm

#5119 Set minimum ARC runners to 0
  .github/arc-runner-config.yaml
Labels: CLA Signed

#5121 Add torchao to Dr CI
  .github/workflows/update-drci-comments.yml
  torchci/lib/bot/utils.ts
Labels: CLA Signed

#5123 [HUD] Fix DataGrid widget not scrolling on metrics page
  torchci/components/metrics/panels/TablePanel.tsx
Labels: CLA Signed

#5124 [HUD] Show workflow startup failures on PR/commit page
  torchci/lib/fetchCommit.ts
  torchci/rockset/commons/__sql/commit_jobs_query.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5115 Fix AWS credentials for update_ci_wait_time_metric.yml workflow
  .github/workflows/update_ci_wait_time_metric.yml
Labels: CLA Signed

#5116 Use the correct conda token for pytorch-test channel
  .github/workflows/anaconda-prune.yml
Labels: CLA Signed

#5122 Support marking unstable jobs from other repos
  torchci/components/CommitStatus.tsx
  torchci/components/FilteredJobList.tsx
  torchci/components/GroupJobConclusion.tsx
  torchci/components/JobLinks.tsx
  torchci/components/JobSummary.tsx
  torchci/components/WorkflowBox.tsx
  torchci/lib/JobClassifierUtil.ts
  torchci/lib/fetchHud.ts
  torchci/lib/jobUtils.ts
  torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
  torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
  torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/pages/failure.tsx
  torchci/pages/flakytest.tsx
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#5135 [EZ] update boto3 (Fix AWS credentials for update_ci_wait_time_metric.yml workflow)
  .github/workflows/update_ci_wait_time_metric.yml
Labels: CLA Signed

#5134 [HUD] Fix more like this/failures page
  torchci/lib/drciUtils.ts
  torchci/lib/searchUtils.ts
  torchci/pages/api/failure.ts
  torchci/test/drciUtils.test.ts
  torchci/test/searchUtils.test.ts
Labels: CLA Signed

#5138 [EZ] Use correct account (Fix AWS credentials for update_ci_wait_time_metric.yml workflow)
  .github/workflows/update_ci_wait_time_metric.yml
Labels: CLA Signed

#5137 Fix missing job on HUD due to wrongly trie match
  torchci/lib/jobUtils.ts
  torchci/test/jobUtils.test.ts
Labels: CLA Signed

#5131 Update Dr.CI to use the list of unstable issues
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#5140 Fix PACKAGE_ALLOW_LIST for torchtune packages
  s3_management/manage.py
Labels: CLA Signed

#5127 [bots] Autolabeler: label to label
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/utils.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed

#5112 [ez] Give content write permissions for update td rating files workflow and reduce data range
  .github/workflows/update_test_file_ratings.yml
  tools/torchci/td/calculate_file_test_rating.py
  tools/torchci/td/utils.py
Labels: CLA Signed

#5141 [HUD] Add tooltip on timestamps for how long ago
  torchci/components/TimeUtils.tsx
Labels: CLA Signed

#5142 Add torchao to allowlist of s3 packages
  s3_management/manage.py
Labels: CLA Signed

#5130 Update default nvidia driver version for incoming CUDA 12.4
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#5145 Update antlr4-python3-runtime
  s3_management/manage.py
Labels: CLA Signed

#5125 [HUD] Better separators for job info, do not show raw log link if no raw link provided, add commit link to job tooltip
  torchci/components/JobLinks.tsx
  torchci/components/JobTooltip.tsx
  torchci/components/ReproductionCommand.tsx
  torchci/components/TestInsights.tsx
  torchci/components/WorkflowBox.tsx
  torchci/package-lock.json
  torchci/package.json
  torchci/pages/failedjobs/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/yarn.lock
Labels: CLA Signed

#5147 Use antlr4 as allowed package
  s3_management/manage.py
Labels: CLA Signed

#5148 Revert "Use antlr4 as allowed package (#5147)"
  s3_management/manage.py
Labels: CLA Signed

#5089 Add CPU AMP instance type for Inductor CPU AMP tests
  .github/arc-node-config.yaml
  .github/arc-runner-config.yaml
  .github/scale-config.yml
Labels: CLA Signed

#5152 Advance conda and conda-build nightly versions
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed, with-ssh

#5150 [hud] when esc pressed, clear pinned tooltip before clearing the job filter
  torchci/lib/useTableFilter.ts
Labels: CLA Signed

#5153 [hud][ez] Add tooltip (title) to the force-merged pr numbers
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#5149 Display the related broken trunk (under BROKEN TRUNK) and similar failures (under FLAKY) on Dr.CI
  torchci/lib/drciUtils.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drci.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed
