Repository pytorch/test-infra, pull requests merged in 2024-06, with the labels that each got.

#5289 [log classifier] More test failure rules
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#5277 [TDB] Add button to regenerate test info
  torchci/components/CommitStatus.tsx
  torchci/components/WorkflowBox.tsx
  torchci/components/additionalTestInfo/RerunInfo.tsx
  torchci/components/additionalTestInfo/TestCounts.tsx
  torchci/components/additionalTestInfo/TestInfo.tsx
  torchci/lib/GeneralUtils.ts
  torchci/lib/bot/utils.ts
  torchci/lib/githubFunctions.ts
  torchci/pages/api/auth/[...nextauth].js
  torchci/pages/api/github/dispatch/[repoOwner]/[repoName]/[workflow]/[sha].ts
  torchci/pages/api/log_annotation/[repoOwner]/[repoName]/[annotation].ts
Labels: CLA Signed

#5288 Add a page to navigate disabled issues on HUD
  torchci/components/NavBar.tsx
  torchci/components/ValuePicker.tsx
  torchci/pages/disabled.tsx
  torchci/rockset/commons/__sql/disabled_test_labels.sql
  torchci/rockset/commons/__sql/disabled_tests.sql
  torchci/rockset/commons/disabled_test_labels.lambda.json
  torchci/rockset/commons/disabled_tests.lambda.json
  torchci/rockset/metrics/__sql/disabled_test_historical.sql
  torchci/rockset/metrics/disabled_test_historical.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5293 Update stable version to 2.3.1
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_conda_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_conda.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_conda_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed, module: rocm

#5294 [BE] Use globals in `generate_binary_build_matrix`
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5295 Windows AMI - update cudnn to 9.1.0.70
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Labels: CLA Signed

#5290 [HUD] All and inverse buttons for chart legends
  torchci/components/metrics/panels/TimeSeriesPanel.tsx
Labels: CLA Signed

#5299 Update manage.py - add llnl_hatchet package
  s3_management/manage.py
Labels: CLA Signed

#5300 [log classifier][ez] After #5289: make failed/subfail group non capturing
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#5296 Update s3_management/manage.py
  .github/workflows/update-s3-html.yml
  s3_management/manage.py
Labels: CLA Signed

#5302 [torchao] Fix torchao GraphPanel
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
  torchci/pages/benchmark/compilers.tsx
  torchci/pages/benchmark/torchao.tsx
Labels: CLA Signed

#5305 Increase max runners available for windows.8xlarge.nvidia.gpu to 300
  .github/scale-config.yml
Labels: CLA Signed

#5286 [BE] Improve documentation of somewhat ambiguous terraform variables
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#5301 Disable py3.12 wheel builds for ROCm
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm

#5303 Fix labels race condition
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#5307 [BE] Print `docker exec` instruction during SSH step
  .github/workflows/linux_job.yml
Labels: CLA Signed

#5306 [torchao] Fix the model graph panel
  torchci/components/benchmark/common.tsx
  torchci/components/benchmark/compilers/ModelGraphPanel.tsx
  torchci/components/benchmark/compilers/ModelPanel.tsx
  torchci/components/benchmark/compilers/SummaryPanel.tsx
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
  torchci/pages/benchmark/compilers.tsx
  torchci/pages/benchmark/torchao.tsx
Labels: CLA Signed

#5309 Add a new section on Dr.CI for canncelled jobs
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#5311 Adds support for newer Amazon Linux 2023
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5283 Add CPU m4.10xlarge instance type for Inductor CPU FP32 accuracy test with AVX2
  .github/arc-node-config.yaml
  .github/arc-runner-config.yaml
  .github/scale-config.yml
Labels: CLA Signed

#5314 [torchao] Update torchao_query version
  torchci/rockset/inductor/__sql/torchao_query.sql
  torchci/rockset/inductor/torchao_query.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5308 Check for similar known unrelated failures in the same PR
  torchci/lib/drciUtils.ts
  torchci/lib/jobUtils.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#5315 Add new trtion dependencies to download.pytorch.org
  s3_management/update_dependencies.py
Labels: CLA Signed, module: rocm, ciflow/rocm

#5317 Add new trtion dependencies to allow list
  s3_management/manage.py
Labels: CLA Signed

#5318 Don't run post-install script for windows runners
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.ps1
Labels: CLA Signed

#5313 [HUD] Optimize some sql queries, add periodic inductor workflows to load chart
  torchci/rockset/commons/__sql/commit_failed_jobs.sql
  torchci/rockset/commons/__sql/pr_commits.sql
  torchci/rockset/commons/__sql/recent_pr_workflows_query.sql
  torchci/rockset/metrics/__sql/workflow_load.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5320 Add textx depdendency when python < 3.10
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#5321 Add importlib-resources
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#5322 Add zipp s3 packages
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#5319 [BE] Add readme for AWS runners
  terraform-aws-github-runner/README.md
  terraform-aws-github-runner/architecture-diagram.png
Labels: CLA Signed

#5325 [cuda] Add support for CUDA 12.4 in `test` channel
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5327 Switch to ${{ runner.temp }}
  .github/workflows/linux_job.yml
Labels: CLA Signed

#5332 Allow having 2 versions of torch in nightly for fallback
  .github/scripts/anaconda-prune/prune.sh
Labels: CLA Signed

#5333 Fix packer setup steps for Windows AMI builds
  aws/ami/windows/README.md
  aws/ami/windows/plugins.pkr.hcl
Labels: CLA Signed

#5337 Windows AMI Pin vs 2022 to older msvc release
  aws/ami/windows/scripts/Installers/Install-VS.ps1
Labels: CLA Signed

#5335 Add workflow to validate Windows AMI packer config
  .github/workflows/windows-ami-validation.yml
Labels: CLA Signed

#5341 [Windows AMI] Improve setup instructions and explain what happens beh…
  aws/ami/windows/README.md
Labels: CLA Signed

#5338 Workaround for Windows AMI conda install step failing
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#5323 Apply isFailureFromPrevMergeCommit logic to all similar failures
  torchci/lib/drciUtils.ts
  torchci/lib/jobUtils.ts
  torchci/pages/api/drci/drci.ts
  torchci/test/drciBot.test.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#5343 Set the correct repo link in mark unstable job button in commit and PR pages
  torchci/components/CommitStatus.tsx
Labels: CLA Signed

#5312 [mergebot] Set mergebot to be configured via config
  torchci/lib/bot/pytorchBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
  torchci/test/utils.ts
Labels: CLA Signed

#5334 Limit the list of similar failures to only main and merge commits
  torchci/lib/commitUtils.ts
  torchci/lib/drciUtils.ts
  torchci/test/drciUtils.test.ts
Labels: CLA Signed

#5348 Switch to ${{ runner.temp }} (#5327)
  .github/workflows/linux_job.yml
Labels: CLA Signed

#5330 Adds kernel-modules-extra and fixes nvida yum repo url for amazon linux 23
  .github/actions/setup-nvidia/action.yml
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5350 Fix Install-Choco-GenerateProfile step
  aws/ami/windows/scripts/Installers/Install-Choco-GenerateProfile.ps1
  aws/ami/windows/scripts/Installers/Install-Choco.ps1
  aws/ami/windows/scripts/Installers/Install-Miniconda3.ps1
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#5355 Adjust anaconda prune logic
  .github/scripts/anaconda-prune/prune.sh
Labels: CLA Signed

#5351 Update test times: Allow dash in test config
  torchci/rockset/commons/__sql/test_time_per_class.sql
  torchci/rockset/commons/__sql/test_time_per_class_periodic_jobs.sql
  torchci/rockset/commons/__sql/test_time_per_file.sql
  torchci/rockset/commons/__sql/test_time_per_file_periodic_jobs.sql
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5356 Remove dependency on legacy ssl
  .github/workflows/lambda-runners.yml
  terraform-aws-github-runner/modules/runners/lambdas/runners/package.json
  terraform-aws-github-runner/modules/runners/lambdas/runners/yarn.lock
Labels: CLA Signed

#5358 Retry dnf commands + always install dev tools
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5344 Add dtype and device columns
  torchci/components/benchmark/llms/ModelGraphPanel.tsx
  torchci/components/benchmark/llms/SummaryPanel.tsx
  torchci/components/benchmark/llms/common.tsx
  torchci/lib/benchmark/llmUtils.ts
  torchci/pages/benchmark/llms.tsx
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_branches.sql
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_llms.sql
  torchci/rockset/benchmarks/__sql/oss_ci_benchmark_names.sql
  torchci/rockset/benchmarks/oss_ci_benchmark_llms.lambda.json
  torchci/rockset/prodVersions.json
Labels: CLA Signed

#5359 Add `linux-aarch64` dispatch
  torchci/components/WorkflowDispatcher.tsx
Labels: CLA Signed

#5361 [BE] Add `fail-silently` option to setup-ssh
  .github/actions/setup-ssh/action.yml
  .github/actions/setup-ssh/index.js
  setup-ssh/src/main.ts
Labels: CLA Signed

#5354 add Testing overhead dashboard to navbar
  torchci/components/NavBar.tsx
Labels: CLA Signed

#5363 Add torch_no_python to s3 allow list
  s3_management/manage.py
Labels: CLA Signed

#5364 [Split Build] Add split build to binary build generation
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5369 fix typo
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#5360 Adds the options 'ami' and 'labels' to scale-config.yml
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#5372 Increase max runners available for linux.24xl.spr-metal, linux.16xlarge.spr, linux.16xlarge.nvidia.gpu
  .github/scale-config.yml
Labels: CLA Signed

#5373 fix user_data.sh for linux instances - retry command not found
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5371 [Split Build] Fix generate_binary_build_matrix unit tests
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#5365 Handle cancelled timeout step on Dr.CI
  torchci/lib/drciUtils.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#5367 [BE][EZ] Reduce unnecessary windows AMI uploading
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#5376 Add g6.4xlarge runner type
  .github/scale-config.yml
Labels: CLA Signed

#5379 Add ability to turn off rocm for validations of domain library
  .github/workflows/validate-domain-library.yml
Labels: CLA Signed, module: rocm, ciflow/rocm

#5374 Improve autoscale lambda release documentation and ease of use
  .github/workflows/lambda-release-tag-runners.yml
  terraform-aws-github-runner/README.md
Labels: CLA Signed

#5378 Replaces the retry mechanism from a reusable code to a function for user-data.sh
  terraform-aws-github-runner/modules/runners-instances/templates/install-config-runner.sh
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#5380 [EZ] Fix typo `aphaNumeric`->`alphaNumeric`
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
Labels: CLA Signed

#5381 Add `-` to alphaNum character set
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
Labels: CLA Signed

#5382 Revert "Add g6.4xlarge runner type"
  .github/scale-config.yml
Labels: CLA Signed
