Repository pytorch/test-infra, pull requests merged in 2025-04, with the labels that each got.

#6489 [HUD] fix query for experiment returning nonsensical numbers
  torchci/clickhouse_queries/experiment_rollover_percentage/query.sql
Labels: CLA Signed

#6487 [HUD] Merge ephemeral job columns on HUD with their non ephemeral counterparts
  torchci/lib/JobClassifierUtil.ts
  torchci/lib/fetchHud.ts
  torchci/lib/types.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#6491 Remove manylinux2014 based builds support logic
  .github/actions/binary-upload/action.yml
  .github/actions/setup-binary-builds/action.yml
  .github/workflows/_binary_upload.yml
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#6492 [Cherry-Pick] Remove cuda 12.6 aarch (#6409) to release 2.7
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6484 Script to get sizes of all s3 buckets
  tools/analytics/get_s3_bucket_sizes.py
Labels: CLA Signed

#6490 [BE] Remove duplicate, stale copy of github_analyze script
  tools/analytics/github_analyze.py
  tools/torchci/github_analyze.py
  tools/torchci/reverts.py
Labels: CLA Signed

#6496 [ez][HUD] Add darkmode for scroll to highlight
  torchci/lib/useScrollTo.ts
  torchci/styles/globals.css
Labels: CLA Signed

#6498 [BE] [Bot] Add --into as an alias for --onto in cherry-pick command
  torchci/lib/bot/cliParser.ts
  torchci/test/cliParser.test.ts
Labels: CLA Signed

#6494 [ez][bot] Add ci-no-td label on PRs titled revert
  torchci/lib/bot/autoLabelBot.ts
  torchci/test/autoLabelBot.test.ts
Labels: CLA Signed

#6497 add logic to store github labeled webhook event to DynamoDB
  torchci/lib/bot/webhookToDynamo.ts
  torchci/test/fixtures/webhookToDynamoExpected.json.gz
  torchci/test/wehookToDynamoBot.test.ts
Labels: CLA Signed

#6502 Copy over issues_label_event from DynamoDB to Clickhouse
  aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
Labels: CLA Signed

#6503 [HUD][dark-mode]: Update JobLinks buttons to use theme variables for dark mode visibility
  torchci/components/JobLinks.module.css
Labels: CLA Signed

#6467 [Step 2/4] Queue Time Histgram
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
  aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
Labels: CLA Signed

#6505 [Queue Time Histogram] Add deployment step
  .github/workflows/lambda-do-release-runners.yml
Labels: CLA Signed

#6504 [Queue Time Histogram] Add Histogram Generator
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
  aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
Labels: CLA Signed

#6507 [Remove cache] Fix concurrent issue
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
Labels: CLA Signed

#6495 [ez][HUD] Move inductor periodic workflows into its own group
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#6509 [validations] Set MATRIX_GPU_ARCH_VERSION for amazon linux 2023 test
  .github/workflows/validate-linux-binaries.yml
Labels: CLA Signed

#6510 [BE] Do not pollute logs with progress bars
  .github/workflows/validate-linux-binaries.yml
Labels: CLA Signed

#6508 [Queue Time Histogran][Fetch Github Config File -> find closest commit config file
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
  aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
Labels: CLA Signed

#6511 Update MACOSX_DEPLOYMENT_TARGET 10.13 -> 10.15
  tools/pkg-helpers/pytorch_pkg_helpers/macos.py
Labels: CLA Signed

#6513 [tritonbench] Add triton compile time dashboard
  torchci/clickhouse_queries/tritonbench_benchmark/params.json
  torchci/clickhouse_queries/tritonbench_benchmark/query.sql
  torchci/clickhouse_queries/tritonbench_benchmark_branches/params.json
  torchci/clickhouse_queries/tritonbench_benchmark_branches/query.sql
  torchci/components/NavBar.tsx
  torchci/components/benchmark/tritonbench/TimeSeries.tsx
  torchci/lib/benchmark/tritonbench/compileTimeUtils.tsx
  torchci/lib/benchmark/tritonbench/tritonSuites.tsx
  torchci/lib/types.ts
  torchci/pages/tritonbench/compile_time.tsx
Labels: CLA Signed

#6515 [BE][HUD] Clean up UI by adding a dropdown for settings
  torchci/components/SettingsPanel.tsx
  torchci/components/hud.module.css
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#6463 Commandline option for github workflow to run android and apple perf workflows
  tools/device-farm-runner/run_perf_workflow.py
Labels: CLA Signed

#6518 Fix tool/torchci test dependency
  tools/torchci/pyproject.toml
  torchci/lib/error_utils.ts
Labels: CLA Signed

#6519 [type] Disable the local test without verify
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
Labels: CLA Signed

#6521 Fixes for query 'experiment_rollover_percentage' introduced on lf_rollover_percentage
  torchci/clickhouse_queries/experiment_rollover_percentage/query.sql
Labels: CLA Signed

#6517 Git Job Error Handling
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6522 [validation] Fix timing out macos validations, add numpy 1.26 validations for python <=3.12
  .github/scripts/validate_binaries.sh
Labels: CLA Signed

#6526 Hud: mark groups with successfully cancelled jobs as warnings
  torchci/components/GroupJobConclusion.tsx
  torchci/lib/jobUtils.ts
Labels: CLA Signed

#6523 Git Job Level Failure
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/lib/benchmark/llms/common.ts
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6528 Remove test data
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6530 Upgrade NVIDIA driver for CUDA 12.6+
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#6529 mergebot: Block PR merges if changes requested
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#6520 Add experiment/stress test code
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
Labels: CLA Signed

#6532 Update NVIDIA driver to 570.133.07 when launching the runner
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6499 Custom script path and tag prefix for calculate docker image
  .github/actions/calculate-docker-image/action.yml
Labels: CLA Signed

#6538 Manylinux 2.28 make sure wheels are renamed
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#6540 [Cherry-Pick] Manylinux 2.28 make sure wheels are renamed
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#6539 Fix env variable bug
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
Labels: CLA Signed

#6534 Expand script to collect dates for the pytorch/docs dir
  .github/scripts/get_tutorials_stats.py
  .github/workflows/upload-tutorials-stats.yml
Labels: CLA Signed

#6541 Remove package/deploy from autolabelbot.ts
  torchci/lib/bot/autoLabelBot.ts
Labels: CLA Signed

#6544 [ez][HUD] Set color for darkmode sev banner
  torchci/components/SevReport.module.css
  torchci/styles/globals.css
Labels: CLA Signed

#6546 [Release 2.7] Update pypi staging scripts
  release/pypi/promote_pypi_to_staging.sh
  release/pypi/upload_pypi_to_staging.sh
  release/release_versions.sh
Labels: CLA Signed

#6548 Fix tutorials stats workflow to checkout the correct repo
  .github/workflows/upload-tutorials-stats.yml
Labels: CLA Signed

#6547 Fix log in lambda
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
Labels: CLA Signed

#6551 [Cherry-PIck] Repair Manylinux 2.28 wheels #6549
  .github/scripts/repair_manylinux_2_28.sh
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#6550 [CH] optimize hud_query by eliminating joins
  torchci/clickhouse_queries/hud_query/params.json
  torchci/clickhouse_queries/hud_query/query.sql
Labels: CLA Signed

#6554 [Release 2.7] Update Binary Build Matrix
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed, module: rocm

#6552 [CH] optimize master_commit_red_jobs by eliminating join and adding pre-filtering
  torchci/clickhouse_queries/master_commit_red_jobs/params.json
  torchci/clickhouse_queries/master_commit_red_jobs/query.sql
Labels: CLA Signed

#6557 [Autoscaler] Add logging to better understand why a scale down occurred
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Labels: CLA Signed

#6531 Queue time histogram [First Iteration]
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_job_name/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_job_name/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_machine_type/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_machine_type/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_workflow_name/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_workflow_name/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_search_items/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_search_items/query.sql
  torchci/components/LoadingPage.tsx
  torchci/components/common/CheckBoxList.tsx
  torchci/components/metrics/pickers/ToggleIconPicker.tsx
  torchci/components/queueTimeAnalysis/QueueTimeAnalysisPage.tsx
  torchci/components/queueTimeAnalysis/components/DebugToggle.tsx
  torchci/components/queueTimeAnalysis/components/QueueTimeChartPage.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeCharts.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
  torchci/components/queueTimeAnalysis/components/pickers/DateRangePicker.tsx
  torchci/components/queueTimeAnalysis/components/pickers/TimeGranuityPicker.tsx
  torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeCheckBoxList.tsx
  torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeSearchBar.tsx
  torchci/lib/GeneralUtils.ts
  torchci/pages/queue_time_analysis.tsx
Labels: CLA Signed

#6556 Single View Table Improvement for benchmark
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
Labels: CLA Signed

#6562 Wdvr/darkmode fix queuetime dark mode colors
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeCharts.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
  torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeCheckBoxList.tsx
Labels: CLA Signed

#6558 [validations] Fix stable cuda validation for pypi release. Cleanup unused code.
  .github/scripts/validate_pipy.sh
  .github/scripts/validate_poetry.sh
  .github/workflows/validate-linux-binaries.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6565 [release] Update promotion scripts to download.pytorch.org
  release/promote.sh
  release/release_versions.sh
Labels: CLA Signed

#6560 [tritonbench] Add benchmark picker
  torchci/clickhouse_queries/tritonbench_list_benchmarks/params.json
  torchci/clickhouse_queries/tritonbench_list_benchmarks/query.sql
  torchci/components/NavBar.tsx
  torchci/components/benchmark/BenchmarkPicker.tsx
  torchci/components/benchmark/RepositoryPicker.tsx
  torchci/components/benchmark/common.tsx
  torchci/components/benchmark/tritonbench/TimeSeries.tsx
  torchci/components/tritonbench/common.tsx
  torchci/lib/benchmark/tritonbench/metricUtils.tsx
  torchci/pages/tritonbench/commit_view.tsx
Labels: CLA Signed

#6570 [Release] fbgemm_gpu and fbgemm_gpu_genai. Cleanup release sripts
  release/README.md
  release/promote.sh
  release/promote/common_utils.sh
  release/release_versions.sh
Labels: CLA Signed

#6566 [HUD] Hack for rerun disable tests and mem leak regex
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#6575 [S3] Fix up networkx index for UV
  s3_management/manage.py
Labels: CLA Signed

#6572 Fix scaleupchron metrics
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
Labels: CLA Signed

#6577 job cancellation dashboard
  torchci/components/NavBar.tsx
  torchci/pages/job_cancellation_dashboard.tsx
Labels: CLA Signed

#6579 Add device type (public, private) and id
  tools/device-farm-runner/run_on_aws_devicefarm.py
Labels: CLA Signed

#6488 Add deep dive videos for the autoscaler
  terraform-aws-github-runner/README.md
Labels: CLA Signed

#6580 [ch] optimize master_commit_red_percent query
  torchci/clickhouse_queries/master_commit_red_percent/params.json
  torchci/clickhouse_queries/master_commit_red_percent/query.sql
Labels: CLA Signed

#6578 [hud][ch][drci] add api to cache ch queries + cache issues query
  tools/scripts/fetch_latest_green_commit.py
  tools/torchci/clickhouse.py
  tools/torchci/tests/test_ch_query.py
  torchci/lib/clickhouse.ts
  torchci/lib/drciUtils.ts
  torchci/lib/fetchHud.ts
  torchci/lib/fetchIssuesByLabel.ts
  torchci/package.json
  torchci/pages/api/drci/drci.ts
  torchci/yarn.lock
Labels: CLA Signed

#6587 Delete TorchBench from NavBar
  torchci/components/NavBar.tsx
Labels: CLA Signed

#6585 update quickstart UI to remove conda
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/test_generate_binary_build_matrix.py
Labels: CLA Signed

#6592 Upgrade nightly wheels to ROCm6.4
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm, ciflow/rocm
