Repository pytorch/test-infra, pull requests merged in 2025-06, with the labels that each got.

#6691 [BE] Remove old cruft from user-data.sh file
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6680 [Queue Time Analysis]
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_job_name/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_job_name/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_machine_type/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_workflow_name/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_per_workflow_name/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_query/params.json
  torchci/clickhouse_queries/queue_time_analysis/queue_time_query/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_search_items/query.sql
  torchci/components/metrics/pickers/ToggleIconPicker.tsx
  torchci/components/queueTimeAnalysis/components/QueueDataExplanation.tsx
  torchci/components/queueTimeAnalysis/components/QueueTimeChartPage.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeCharts.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
  torchci/components/queueTimeAnalysis/components/pickers/QueueTimeCategoryPicker.tsx
  torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeSearchBar.tsx
Labels: CLA Signed

#6678 [Utilization] Add new time range picker and bunch of reusable UI
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/query.sql
  torchci/components/uiModules/UMCheckboxPopover.tsx
  torchci/components/uiModules/UMCopyLink.tsx
  torchci/components/uiModules/UMDateRangePicker.tsx
  torchci/components/uiModules/UMDenseComponents.tsx
  torchci/components/uiModules/UMDenseDatePicker.tsx
  torchci/components/uiModules/UMMetricsTable.tsx
  torchci/components/uiModules/UMPropReducer.tsx
  torchci/components/utilization/UtilizationReportPage/ReportMetricsTable.tsx
  torchci/components/utilization/UtilizationReportPage/UtilReportPageSyncParamsToUrl.tsx
  torchci/components/utilization/UtilizationReportPage/UtilizationReportContext.tsx
  torchci/components/utilization/UtilizationReportPage/UtilizationReportPage.tsx
  torchci/components/utilization/UtilizationReportPage/hepler.ts
  torchci/lib/utilization/fetchListUtilizationReport.ts
  torchci/lib/utilization/types.ts
Labels: CLA Signed

#6693 [ez][HUD] Disabled tests page: Changes to query params and other small things
  torchci/clickhouse_queries/disabled_test_labels/params.json
  torchci/clickhouse_queries/disabled_test_labels/query.sql
  torchci/lib/GeneralUtils.ts
  torchci/pages/disabled.tsx
Labels: CLA Signed

#6699 Add nvidia_nvshmem_cu12 to list of allowed files
  s3_management/manage.py
Labels: CLA Signed

#6701 Release 2.7.1 update stable version
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed, module: rocm

#6676 [bots] Move the disable json generation to be in HUD
  .github/scripts/test_update_disabled_issues.py
  .github/scripts/update_disabled_issues.py
  .github/workflows/tests.yml
  .github/workflows/update_disabled_tests.yml
  torchci/lib/flakyBot/aggregateDisableIssue.ts
  torchci/lib/flakyBot/singleDisableIssue.ts
  torchci/lib/flakyBot/utils.ts
  torchci/pages/api/flaky-tests/getDisabledTestsAndJobs.ts
  torchci/test/flakyBotTests/flakyBotIntegration.test.ts
  torchci/test/flakyBotTests/flakyBotTestsUtils.ts
  torchci/test/flakyBotTests/flakySingleIssue.test.ts
  torchci/test/flakyBotTests/getDisabledTestsAndJobs.test.ts
  torchci/test/utils.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#6687 [bots] Generate historical data for flaky/disabled tests when updating disabled tests condensed json
  .github/scripts/gen_historical_disabled_issue_data.py
  .github/scripts/update_disabled_issues.py
  .github/workflows/update_disabled_tests.yml
  aws/lambda/clickhouse-replicator-s3/lambda_function.py
  clickhouse_db_schema/misc.disabled_tests_historical/schema.sql
Labels: CLA Signed

#6682 [Lambda: Tracking AWS CE] Generate running data from AWS CE
  .github/workflows/lambda-do-release-runners.yml
  aws/lambda/oss_ci_cur/.gitignore
  aws/lambda/oss_ci_cur/Makefile
  aws/lambda/oss_ci_cur/Readme.md
  aws/lambda/oss_ci_cur/lambda_function.py
  aws/lambda/oss_ci_cur/requirements.txt
  aws/lambda/tests/common.py
  aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
  aws/lambda/tests/test_lambda_oss_cur.py
  clickhouse_db_schema/oss_ci_cur_schema/schema.sql
Labels: CLA Signed

#6089 [HUD] additional test info - better ui for reruns/failures
  torchci/components/additionalTestInfo/RerunInfo.tsx
Labels: CLA Signed

#6705 [ez][HUD] host -> url for clickhouse client
  torchci/lib/clickhouse.ts
Labels: CLA Signed

#6708 [CH][BE][ez] Make queries on TTS page faster by removing join
  torchci/clickhouse_queries/tts_duration_historical/query.sql
  torchci/clickhouse_queries/tts_duration_historical_percentile/query.sql
Labels: CLA Signed

#6425 Add a script to gather runner info when uploading benchmark results
  .github/actions/upload-benchmark-results/action.yml
  .github/scripts/benchmark-results-dir-for-testing/v2/android-artifacts-31017223108.json
  .github/scripts/benchmark-results-dir-for-testing/v2/android-artifacts-31017223431.json
  .github/scripts/benchmark-results-dir-for-testing/v3/do_not_overwrite_runners_info.json
  .github/scripts/benchmarks/gather_runners_info.py
  .github/workflows/test_upload_benchmark_results.yml
Labels: CLA Signed

#6711 [ez][disabled tests] Fix historical records json not being uploaded to s3 in upload disable tests workflow
  .github/workflows/update_disabled_tests.yml
Labels: CLA Signed

#6712 [proposal] Add banner for github action issue
  torchci/components/githubIncident/GithubIncident.tsx
  torchci/pages/_app.tsx
Labels: CLA Signed

#6709 [BE][Refresh-runner 1.5/4][BE] reorg the tryReuse method into small pieces
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
Labels: CLA Signed

#6713 [Fix the date conversion issue] [CUR]
  aws/lambda/oss_ci_cur/lambda_function.py
Labels: CLA Signed

#6717 AO Benchmark
  torchci/components/NavBar.tsx
  torchci/components/benchmark/llms/components/LLMsReport.tsx
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6721 tools: Update clear_offline_runners to clear ec2
  .lintrunner.toml
  tools/self-hosted-runner-utils/clear_offline_runners.py
  tools/self-hosted-runner-utils/requirements.txt
Labels: CLA Signed

#6714 [queue alert] Close issue if too many comments
  tools/torchci/check_alerts.py
  tools/torchci/queue_alert.py
  tools/torchci/tests/test_check_alerts.py
Labels: CLA Signed

#6733 [BE] Rename reusable workflow to have the usual prefix
  .github/workflows/_lambda-do-release-runners.yml
  .github/workflows/lambda-release-tag-runners.yml
  aws/lambda/README.md
Labels: CLA Signed

#6742 Windows AMI Update cudnn for cuda 12.6 and 12.8
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Labels: CLA Signed

#6737 [ez] Clear offline runners: fetch from aws first
  tools/self-hosted-runner-utils/clear_offline_runners.py
Labels: CLA Signed

#6748 [AMI] Remove CUDA 11.8 install
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#6754 Use 12.6.3 for CUDA 12.6 windows installation script
  aws/ami/windows/scripts/Installers/Install-CUDA-Tools.ps1
Labels: CLA Signed

#6750 Install wiz sensor on linux runners
  terraform-aws-github-runner/modules/runners-instances/launch-template.tf
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#6757 [pytorchbot] Remove reference to the `close` command
  torchci/lib/bot/cliParser.ts
Labels: CLA Signed

#6758 ccleanup/split of McpQueryPage
  torchci/components/McpQueryPage.tsx
  torchci/components/McpQueryPage/GrafanaEmbed.tsx
  torchci/components/McpQueryPage/TodoList.tsx
  torchci/components/McpQueryPage/ToolUse.tsx
  torchci/components/McpQueryPage/hooks.ts
  torchci/components/McpQueryPage/styles.ts
  torchci/components/McpQueryPage/types.ts
  torchci/components/McpQueryPage/utils.tsx
Labels: CLA Signed

#6696 Hack/grafana mcp
  aws/lambda/README.md
  torchci/.env.example
  torchci/components/AISpinner.tsx
  torchci/components/McpQueryPage.tsx
  torchci/components/McpQueryPage/GrafanaEmbed.tsx
  torchci/components/McpQueryPage/TodoList.tsx
  torchci/components/McpQueryPage/ToolUse.tsx
  torchci/components/McpQueryPage/hooks.ts
  torchci/components/McpQueryPage/styles.ts
  torchci/components/McpQueryPage/types.ts
  torchci/components/McpQueryPage/utils.tsx
  torchci/components/ToolIcon.tsx
  torchci/pages/api/grafana_mcp/index.ts
  torchci/pages/mcp_query.tsx
  torchci/public/icons/bash_icon.svg
  torchci/public/icons/clickhouse_icon.png
  torchci/public/icons/grafana_icon.svg
Labels: CLA Signed

#6762 Overlap date for oss_ci_cur
  aws/lambda/oss_ci_cur/lambda_function.py
Labels: CLA Signed

#6768 API to fetch all data in the format of data table for benchmark result
  torchci/lib/datamodels/benchmark_group_request.ts
  torchci/lib/datamodels/zodUtils.ts
  torchci/package.json
  torchci/pages/api/benchmark/group_data.ts
  torchci/yarn.lock
Labels: CLA Signed

#6761 add CUDA 12.9 domain builds for linux
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
Labels: CLA Signed, module: rocm

#6771 Add issue shortcut buttons on TorchAgent page
  torchci/components/TorchAgentPage.tsx
Labels: CLA Signed, codex

#6776 [torchagent] add username to lambda call
  torchci/pages/api/grafana_mcp/index.ts
Labels: CLA Signed

#6720 Creates placeholder for autorevert lambda
  .github/workflows/_lambda-do-release-runners.yml
  aws/lambda/pytorch-auto-revert/.gitignore
  aws/lambda/pytorch-auto-revert/Makefile
  aws/lambda/pytorch-auto-revert/auto_revert.py
  aws/lambda/pytorch-auto-revert/requirements.txt
Labels: CLA Signed, ci-no-td

#6784 Add r5.16xlarge and r5.24xlarge to match their c5 counterparts
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6779 Add TorchAgent feedback recording
  clickhouse_db_schema/misc.torchagent_feedback/schema.sql
  torchci/components/TorchAgentPage.tsx
  torchci/components/TorchAgentPage/FeedbackButtons.tsx
  torchci/pages/api/torchagent-feedback.ts
  torchci/test/torchagentFeedback.test.ts
Labels: CLA Signed, codex

#6787 [HUD] Make GH incident banner style closer to sev report style
  torchci/components/githubIncident/GithubIncident.tsx
Labels: CLA Signed

#6789 [TD] Fix file ratings workflow: upgrade boto3, make query faster, timezone api deprecation
  .github/workflows/update_test_file_ratings.yml
  tools/torchci/td/get_merge_base_info.py
Labels: CLA Signed

#6796 Use windows.8xlarge.memory, remove unused instance windows.9xlarge
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6775 [torchagent] cleaner UI for bug report/ feature request
  torchci/components/TorchAgentPage.tsx
  torchci/components/TorchAgentPage/HeaderSection.tsx
Labels: CLA Signed

#6806 Add sym link for queue time analysis
  torchci/components/queueTimeAnalysis/components/QueueTimeChartPage.tsx
  torchci/components/queueTimeAnalysis/components/charts/QueueTimeEchartElement.tsx
  torchci/components/queueTimeAnalysis/components/searchBarItems/QueueTimeSearchBar.tsx
  torchci/components/uiModules/UMCopyLink.tsx
  torchci/components/utilization/UtilizationReportPage/UtilizationReportPage.tsx
  torchci/components/utilization/UtilizationReportPage/hepler.ts
Labels: CLA Signed

#6807 [Reland] Fix gather_runners_info script on ROCm
  .github/actions/upload-benchmark-results/action.yml
  .github/scripts/benchmarks/gather_runners_info.py
Labels: CLA Signed, module: rocm, ciflow/rocm, ci-no-td

#6766 create workflow to check release milestone for fixed but not cherrypicked issues
  .github/workflows/github-analytics-daily.yml
Labels: CLA Signed

#6810 [benchmark] Fixbug to able to fetch nested fields
  torchci/pages/api/benchmark/group_data.ts
Labels: CLA Signed

#6803 Refactor TorchAgent page loader
  torchci/components/TorchAgentPage.tsx
Labels: CLA Signed, codex

#6821 [ez][lambdas] Update readme after #6809
  aws/lambda/README.md
Labels: CLA Signed

#6828 change instructions for running cut-release-branch script
  release/cut-release-branch.sh
Labels: CLA Signed

#6813 Fix stream continuation on navigation to historic chats
  torchci/components/TorchAgentPage.tsx
Labels: CLA Signed

#6817 Revamp TorchAgent UI
  clickhouse_db_schema/misc.torchagent_feedback/schema.sql
  torchci/components/TorchAgentPage.tsx
  torchci/components/TorchAgentPage/ChatHistorySidebar.tsx
  torchci/components/TorchAgentPage/HeaderSection.tsx
  torchci/components/TorchAgentPage/LoadingDisplay.tsx
  torchci/components/TorchAgentPage/QueryInputSection.tsx
  torchci/components/TorchAgentPage/hooks.ts
  torchci/components/TorchAgentPage/messageProcessor.ts
  torchci/components/TorchAgentPage/styles.ts
  torchci/components/TorchAgentPage/types.ts
  torchci/components/TorchAgentPage/utils.tsx
  torchci/pages/api/torchagent-api/index.ts
Labels: CLA Signed, codex

#6829 [Cleanup]move to existing misc instead of fortesting db table
  aws/lambda/oss_ci_job_queue_time/lambda_function.py
  aws/lambda/tests/test_lambda_oss_ci_job_queue_time.py
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_metadata/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_ts/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_query/query.sql
  torchci/clickhouse_queries/queue_time_analysis/queue_time_search_items/query.sql
Labels: CLA Signed

#6836 Enable specifying whether or not to pull the docker image from ECR
  .github/actions/calculate-docker-image/action.yml
  .github/workflows/linux_job_v2.yml
Labels: CLA Signed

#6838 Add windows 12.9 domain builds
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#6834 Add method to analyze reverts: analyze_reverts_missing_from_branch
  tools/analytics/github_analyze.py
Labels: CLA Signed, ci-no-td

#6844 Cherry pick of Add Windows 12.9 domain builds #6838
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#6846 rename torchagent to flambeau
  torchci/components/NavBar.tsx
  torchci/components/TorchAgentPage/HeaderSection.tsx
  torchci/components/TorchAgentPage/TipsInfoButton.tsx
  torchci/components/TorchAgentPage/WelcomeSection.tsx
  torchci/pages/flambeau.tsx
Labels: CLA Signed

#6847 Add miniconda install=true to build_wheels_macos.yml
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#6850 Cherry Pick of M1 build #6847
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed

#6852 runners: Add batching for terminateRunner
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Labels: CLA Signed

#6854 runners: More scale-down perf improvements
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
Labels: CLA Signed

#6849 [ez][disablebot] Lower threshold for creating aggregate flaky issues 10 -> 4
  torchci/pages/api/flaky-tests/disable.ts
Labels: CLA Signed

#6861 aws: Add pagination, progress bars, and human time
  aws/tools/cleanup-ssm/Cargo.toml
  aws/tools/cleanup-ssm/src/cleanup.rs
  aws/tools/cleanup-ssm/src/client.rs
  aws/tools/cleanup-ssm/src/filter.rs
  aws/tools/cleanup-ssm/src/lib.rs
  aws/tools/cleanup-ssm/src/main.rs
Labels: CLA Signed

#6860 [disablebot] Fix aggregate issues getting auto closed
  torchci/pages/api/flaky-tests/disable.ts
  torchci/test/flakyBotTests/flakyBotUtils.test.ts
Labels: CLA Signed

#6870 aws: Add regex pattern matching to cleanup-ssm tool
  aws/tools/cleanup-ssm/Cargo.toml
  aws/tools/cleanup-ssm/src/filter.rs
  aws/tools/cleanup-ssm/src/lib.rs
  aws/tools/cleanup-ssm/src/main.rs
Labels: CLA Signed

#6871 aws: Add const for ONE_DAY_IN_SECONDS
  aws/tools/cleanup-ssm/src/filter.rs
  aws/tools/cleanup-ssm/src/lib.rs
Labels: CLA Signed

#6864 Only add symm memory code path for auto labeling of h100-distributed
  torchci/lib/bot/autoLabelBot.ts
Labels: CLA Signed
