Repository pytorch/test-infra, pull requests merged in 2025-05, with the labels that each got.

#6593 [Device ID] visualize benchmark graph with group_key
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/lib/benchmark/llms/common.ts
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6595 Separate private and public devices on benchmark dashboard
  torchci/clickhouse_queries/oss_ci_benchmark_branches/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/clickhouse_queries/oss_ci_benchmark_names/query.sql
Labels: CLA Signed

#6594 [tritonbench] Exclude low_mem_dropout from the data to avoid zeros.
  torchci/components/benchmark/tritonbench/TimeSeries.tsx
Labels: CLA Signed

#6596 Send metrics before callback() for scaleUpChron
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.ts
Labels: CLA Signed

#6599 [ez][HUD] Expand log search to other repos
  torchci/lib/searchLogs.ts
Labels: CLA Signed

#6597 Improvements to test times queries
  tools/torchci/clickhouse_query_perf.py
  torchci/clickhouse_queries/test_time_per_class/params.json
  torchci/clickhouse_queries/test_time_per_class/query.sql
  torchci/clickhouse_queries/test_time_per_class_periodic_jobs/params.json
  torchci/clickhouse_queries/test_time_per_class_periodic_jobs/query.sql
  torchci/clickhouse_queries/test_time_per_file/params.json
  torchci/clickhouse_queries/test_time_per_file/query.sql
  torchci/clickhouse_queries/test_time_per_file_periodic_jobs/params.json
  torchci/clickhouse_queries/test_time_per_file_periodic_jobs/query.sql
Labels: CLA Signed

#6591 Pin to SHA for actions outside of PyTorch
  .github/workflows/_binary_upload.yml
  .github/workflows/_upload_docs.yml
  .github/workflows/backfill-workflow-job.yml
  .github/workflows/build-windows-ami.yml
  .github/workflows/build_wheels_linux.yml
  .github/workflows/build_wheels_macos.yml
  .github/workflows/build_wheels_windows.yml
  .github/workflows/check-alerts.yml
  .github/workflows/clang-tidy-linux.yml
  .github/workflows/clang-tidy-macos.yml
  .github/workflows/clickhouse-replicator-dynamo-lambda.yml
  .github/workflows/clickhouse-replicator-s3-lambda.yml
  .github/workflows/deploy_lambda_whl_metadata_upload_pep658.yml
  .github/workflows/generate_binary_build_matrix.yml
  .github/workflows/generate_docker_release_matrix.yml
  .github/workflows/generate_release_matrix.yml
  .github/workflows/gha-artifacts-lambda.yml
  .github/workflows/github-status-test-lambda.yml
  .github/workflows/lambda-do-release-runners.yml
  .github/workflows/lambda-release-tag-runners.yml
  .github/workflows/lambda-runner-binaries-syncer.yml
  .github/workflows/lambda-runners.yml
  .github/workflows/lambda-webhook.yml
  .github/workflows/lint.yml
  .github/workflows/linux_job.yml
  .github/workflows/linux_job_v2.yml
  .github/workflows/log-classifier-lambda.yml
  .github/workflows/macos_job.yml
  .github/workflows/mobile_job.yml
  .github/workflows/opensearch-gha-jobs-lambda.yml
  .github/workflows/pr-dependencies-check.yml
  .github/workflows/revert-tracker.yml
  .github/workflows/scale_config_validation.yml
  .github/workflows/servicelab-ingestor-lambda.yml
  .github/workflows/test-binary-size-validation.yml
  .github/workflows/test-setup-miniconda.yml
  .github/workflows/test-setup-nvidia.yml
  .github/workflows/test-setup-ssh.yml
  .github/workflows/test_upload_benchmark_results.yml
  .github/workflows/tflint.yml
  .github/workflows/torchci.yml
  .github/workflows/trigger_nightly.yml
  .github/workflows/trigger_nightly_core.yml
  .github/workflows/update-drci-comments.yml
  .github/workflows/update-queue-times.yml
  .github/workflows/update-s3-html.yml
  .github/workflows/update-test-times.yml
  .github/workflows/update_disabled_tests.yml
  .github/workflows/update_test_file_ratings.yml
  .github/workflows/upload-tutorials-stats.yml
  .github/workflows/usage-log-aggregator-lambda.yml
  .github/workflows/validate-pypi-wheel-binary-size.yml
  .github/workflows/windows-ami-validation.yml
  .github/workflows/windows_job.yml
Labels: CLA Signed

#6604 [Mergebot] Adding ciflow/pull in PR without pull and lint workflows
  torchci/clickhouse_queries/get_workflows_for_commit/params.json
  torchci/clickhouse_queries/get_workflows_for_commit/query.sql
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#6606 Revert "[Mergebot] Adding ciflow/pull in PR without pull and lint workflows"
  torchci/clickhouse_queries/get_workflows_for_commit/params.json
  torchci/clickhouse_queries/get_workflows_for_commit/query.sql
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed, ci-no-td

#6600 [bug] logic handle device_ID
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
Labels: CLA Signed

#6613 Release 2.7.1 bump candidate version
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6614 [release] Bump Candidate to 2.7.1, update stable and nightly as well
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6616 Temporarily shrink the interval we wait for during chaos testing
  torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Labels: CLA Signed

#6617 Revert "Temporarily shrink the interval we wait for during chaos testing"
  torchci/clickhouse_queries/queued_jobs_aggregate/query.sql
Labels: CLA Signed, ci-no-td

#6622 [release-only] Update pinned docker images for vision and audio
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed

#6615 Update pr_time_benchmarks log classification rule
  aws/lambda/log-classifier/fixtures/request.json
  aws/lambda/log-classifier/ruleset.toml
Labels: CLA Signed

#6621 Trigger scale-up-cron lambda more frequently
  terraform-aws-github-runner/modules/runners/variables.tf
Labels: CLA Signed

#6612 [XPU] Update runtime pypi package dependencies for 2025.1
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#6624 Fix python 3.13t builds on aarch64
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#6627 [Cherry-Pick] Fix python 3.13t builds on aarch64 #6624
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#6628 Make every runner in scale-config.yml to be ephemeral
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6609 [Uitlization] Aggreggation Report Api
  clickhouse_db_schema/oss_ci_utilization/oss_ci_utilization_job_report_materialized_views.sql
  clickhouse_db_schema/oss_ci_utilization/oss_ci_utilization_summary_report_v1.sql
  clickhouse_db_schema/oss_ci_utilization/oss_ci_utilization_workflow_report_materialized_veiws.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_metadata_info/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_metadata_info/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_stats/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_stats/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_metadata/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_metadata/query.sql
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_ts/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_util_ts/query.sql
  torchci/lib/utilization/fetchListUtilizationMetadataInfo.ts
  torchci/lib/utilization/fetchListUtilizationReport.ts
  torchci/lib/utilization/fetchUtilization.ts
  torchci/lib/utilization/types.ts
  torchci/pages/api/list_util_reports/[group_by].ts
Labels: CLA Signed

#6618 Fix scaleUpChron check for queue time using max_queue_time_minutes
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
  terraform-aws-github-runner/modules/runners/scale-up-chron.tf
Labels: CLA Signed

#6605 Removing ephemeral experiment from scale-config.yml and updating validate_scale_config.py
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
  .github/scripts/validate_scale_config.py
Labels: CLA Signed

#6632 Fix typo after #6612
  s3_management/manage.py
Labels: CLA Signed

#6610 [Mergebot] Adding ciflow/pull in PR without pull and lint workflows
  torchci/clickhouse_queries/get_workflows_for_commit/params.json
  torchci/clickhouse_queries/get_workflows_for_commit/query.sql
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#6553 [BE] Upgrade XPU support package to 2025.1 in Windows CICD
  .github/scripts/install_xpu.bat
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#6635 Add h100 workflow dispatch to HUD
  torchci/components/WorkflowDispatcher.tsx
Labels: CLA Signed

#6631 [ez][HUD] Make main page column width wider
  torchci/components/hud.module.css
Labels: CLA Signed

#6634 [ez][CH][drci] Improve recent_pr_workflows_query perf
  torchci/clickhouse_queries/recent_pr_workflows_query/params.json
  torchci/clickhouse_queries/recent_pr_workflows_query/query.sql
Labels: CLA Signed

#6636 Link to hud disabled view in GH issue
  torchci/pages/api/flaky-tests/disable.ts
Labels: CLA Signed

#6611 demo
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/params.json
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_utilization_reports/query.sql
  torchci/components/NavBar.tsx
  torchci/components/uiModules/MetricsTable.tsx
  torchci/components/utilization/UtilizationReportPage/UtilizationReportPage.tsx
  torchci/components/utilization/UtilizationReportPage/hepler.ts
  torchci/components/utilization/WorkflowUtilizationPage/WorkflowUtilizationPage.tsx
  torchci/components/utilization/components/DenseTable/DenseTable.tsx
  torchci/lib/utilization/types.ts
  torchci/pages/api/list_util_reports/[group_by].ts
  torchci/pages/utilization/report/[[...page]].tsx
Labels: CLA Signed

#6637 ci: Pin more nvidia-container dependencies
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#6638 Check if nvidia-container-toolkit is installed correctly
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#6639 Keep nightly dev20250310 for ExecuTorch
  s3_management/manage.py
Labels: CLA Signed

#6643 Fix s3 update workflow after: #6639
  s3_management/manage.py
Labels: CLA Signed

#6645 [Cherry-Pick] ci: Pin more nvidia-container dependencies #6637
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#6644 pr label event table in dynamo
  aws/lambda/clickhouse-replicator-dynamo/lambda_function.py
  torchci/lib/bot/webhookToDynamo.ts
  torchci/test/wehookToDynamoBot.test.ts
Labels: CLA Signed

#6647 [Improvement] fix row length bug + enable download as excel sheet
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/package-lock.json
  torchci/package.json
  torchci/yarn.lock
Labels: CLA Signed

#6648 Setting Windows Long Path
  .github/actions/setup-windows/action.yml
Labels: CLA Signed

#6650 [flakybot] Move code around (mostly in preparation for allowing the bot to make aggregate issues)
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/lib/flakyBot/singleDisableIssue.ts
  torchci/lib/flakyBot/utils.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/test/flakyBotTests/flakyBotIntegration.test.ts
  torchci/test/flakyBotTests/flakyBotTestsUtils.ts
  torchci/test/flakyBotTests/flakyBotUtils.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#6651 [torchci] Remove package-lock.json, rerun yarn install
  .gitignore
  torchci/package-lock.json
  torchci/yarn.lock
Labels: CLA Signed

#6657 cost dashboard: group by instance type (aws runners)
  torchci/clickhouse_queries/cost_job_per_instance_type/params.json
  torchci/clickhouse_queries/cost_job_per_instance_type/query.sql
  torchci/clickhouse_queries/duration_job_per_instance_type/params.json
  torchci/clickhouse_queries/duration_job_per_instance_type/query.sql
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6656 Add NA as option for most fields in the cost dashboard #6655
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6658 AMD (rocm) in cost dashboard
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed, module: rocm, ciflow/rocm

#6660 [ez][flakybot] Move some tests around
  torchci/test/flakyBotTests/flakyBotIntegration.test.ts
  torchci/test/flakyBotTests/flakyBotUtils.test.ts
  torchci/test/flakyBotTests/flakySingleIssue.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#6642 Add Amazon EC2 M8g Instances
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#6672 allow users to export cost table as csv
  torchci/components/metrics/panels/TimeSeriesTable.tsx
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6673 [BE] refactor csv export for cost dashboard & benchmark
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/components/metrics/panels/TimeSeriesTable.tsx
  torchci/lib/csvUtils.ts
  torchci/package.json
  torchci/yarn.lock
Labels: CLA Signed

#6674 Color fixes for dark mode cost table
  torchci/components/metrics/panels/TimeSeriesTable.tsx
  torchci/lib/csvUtils.ts
  torchci/styles/globals.css
Labels: CLA Signed

#6675 [BE] fix legend overlapping graph
  torchci/components/metrics/panels/TimeSeriesPanel.tsx
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6661 [bots] Change verify disable issues in prep for handling aggregate issues
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/lib/flakyBot/singleDisableIssue.ts
  torchci/lib/flakyBot/utils.ts
  torchci/test/common.ts
  torchci/test/flakyBotTests/flakySingleIssue.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#6649 [bots] Allow flakybot to make aggregate issues
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/lib/flakyBot/aggregateDisableIssue.ts
  torchci/lib/flakyBot/singleDisableIssue.ts
  torchci/pages/api/flaky-tests/disable.ts
  torchci/test/flakyBotTests/flakyAggregateIssue.test.ts
  torchci/test/flakyBotTests/flakyBotIntegration.test.ts
  torchci/test/flakyBotTests/flakyBotTestsUtils.ts
  torchci/test/flakyBotTests/flakyBotUtils.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#6677 Add fbgemm_gpu_genai to allow list
  s3_management/manage.py
Labels: CLA Signed

#6679 [BE] Use python script and auditwheel for wheel file manipulation
  release/pypi/prep_binary_for_pypi.py
  release/pypi/prep_binary_for_pypi.sh
  release/pypi/upload_pypi_to_staging.sh
Labels: CLA Signed

#6683 [BE] Add guidance to set up new lambda in test-infra
  aws/lambda/README.md
Labels: CLA Signed

#6684 [Ephemeral Scale Downs] Reduce min runtime and better track buffer time
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#6690 fix timezone in cost dashboard
  torchci/components/TimeUtils.tsx
  torchci/components/metrics/panels/TimeSeriesPanel.tsx
  torchci/components/metrics/panels/TimeSeriesTable.tsx
  torchci/pages/cost_analysis.tsx
Labels: CLA Signed

#6689 [EZ] Minor typo fix
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed
