Repository pytorch/test-infra, pull requests merged in 2025-09, with the labels that each got.

#7053 [BE][EZ] Document what the enable_organizations_runner param does
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#7072 [BUG]The title are missing in compiler page
  torchci/components/metrics/panels/TablePanel.tsx
Labels: CLA Signed

#7079 [ez][drci] Remove unused mock in test
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#7082 [HUD] Add GitHub Actions runners monitoring dashboard
  torchci/components/layout/NavBar.tsx
  torchci/components/runners/RunnerGroupCard.tsx
  torchci/components/runners/StatusChip.tsx
  torchci/lib/runnerUtils.ts
  torchci/next-env.d.ts
  torchci/pages/api/runners/[org].ts
  torchci/pages/runners/[org].tsx
Labels: CLA Signed

#7073 [Add API] get_time_series
  .gitignore
  torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
  torchci/lib/benchmark/api_helper/compilers/precompute.ts
  torchci/lib/benchmark/api_helper/utils.ts
  torchci/lib/benchmark/compilerUtils.ts
  torchci/lib/clickhouse.ts
  torchci/pages/api/benchmark/get_time_series.ts
Labels: CLA Signed

#7090 fix bug for graph display
  torchci/components/metrics/panels/TablePanel.tsx
Labels: CLA Signed

#7093 [HUD] Update some queries and regex for better viable/strict job definitions
  torchci/clickhouse_queries/master_commit_red/query.sql
  torchci/clickhouse_queries/master_commit_red_avg/query.sql
  torchci/clickhouse_queries/master_commit_red_percent/query.sql
  torchci/components/job/GroupJobConclusion.tsx
  torchci/pages/metrics.tsx
  torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
Labels: CLA Signed

#7077 Upgrade webhook lambda for scale up/down to aws sdk v3
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/package.json
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/src/kms/index.ts
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/src/sqs/index.ts
  terraform-aws-github-runner/modules/webhook/lambdas/webhook/yarn.lock
Labels: CLA Signed

#7061 Upgrade scale up/down lambdas to aws sdk v3
  terraform-aws-github-runner/modules/runners/lambdas/runners/jest.config.js
  terraform-aws-github-runner/modules/runners/lambdas/runners/package.json
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/lambda.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-auth.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-auth.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-issues.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/kms/index.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/kms/index.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/sqs.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/sqs.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/yarn.lock
Labels: CLA Signed

#7108 Add python 3.14 builds for windows
  .github/actions/setup-binary-builds/action.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed

#7116 Set preview docs in PRs to overwrite
  .github/workflows/linux_job_v2.yml
Labels: CLA Signed

#7098 Add capabilities=all when launching cuda container
  .github/workflows/build_wheels_linux.yml
Labels: CLA Signed

#7092 Add lambda to fetch data from api and add conifguration data model
  aws/lambda/benchmark_regression_summary_report/common/benchmark_time_series_api_model.py
  aws/lambda/benchmark_regression_summary_report/common/config.py
  aws/lambda/benchmark_regression_summary_report/common/config_model.py
  aws/lambda/benchmark_regression_summary_report/lambda_function.py
Labels: CLA Signed

#7094 add regression report generator
  aws/lambda/benchmark_regression_summary_report/common/benchmark_time_series_api_model.py
  aws/lambda/benchmark_regression_summary_report/common/regression_utils.py
  aws/lambda/benchmark_regression_summary_report/lambda_function.py
  aws/lambda/benchmark_regression_summary_report/requirements.txt
  clickhouse_db_schema/benchmark_regression_report/schema.sql
Labels: CLA Signed

#7125 improve time series api
  torchci/clickhouse_queries/compilers_benchmark_api_query/params.json
  torchci/clickhouse_queries/compilers_benchmark_api_query/query.sql
  torchci/lib/benchmark/api_helper/compilers/precompute.ts
  torchci/lib/benchmark/api_helper/utils.ts
  torchci/lib/benchmark/compilerUtils.ts
  torchci/lib/types.ts
Labels: CLA Signed

#7133 Fix tests after enabling windows cuda 13.0 PR #7080
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
Labels: CLA Signed

#7114 Surface vLLM wheels (vllm, flashinfer_python, and xformers)
  s3_management/manage.py
Labels: CLA Signed

#7096 add github notification
  aws/lambda/benchmark_regression_summary_report/common/config.py
  aws/lambda/benchmark_regression_summary_report/common/config_model.py
  aws/lambda/benchmark_regression_summary_report/common/report_manager.py
  aws/lambda/benchmark_regression_summary_report/lambda_function.py
Labels: CLA Signed

#7143 Add cuda aarch64 builds to matrix. Update validation release matrix for 2.9
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#7161 [BE] Update flake8 configuration to ignore E203 for Black compatibility
  .flake8
  pyproject.toml
Labels: CLA Signed

#7111 [autorevert] add signal extraction layer for transforming CI data into Signal objects
  aws/lambda/pytorch-auto-revert/SIGNAL_EXTRACTION.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/hud_renderer.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/job_agg_index.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_types.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/hud.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_extraction.py
Labels: CLA Signed, ci-no-td

#7159 Update NVIDIA driver to 580.82.07
  terraform-aws-github-runner/modules/runners-instances/templates/user-data.sh
Labels: CLA Signed

#7170 update torchrec version to V1.3.0
  release/promote.sh
  release/release_versions.sh
Labels: CLA Signed

#7167 [autorevert] non nullable dates & dedup
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/job_agg_index.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_types.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_dedup.py
Labels: CLA Signed, ci-no-td

#7179 [autorevert] Breaks down dry_run logic for revert and restart
  aws/lambda/pytorch-auto-revert/Makefile
  aws/lambda/pytorch-auto-revert/SIGNAL_ACTIONS.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/run_state_logger.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_actions.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_types.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert_v2.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_actions.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/utils.py
Labels: CLA Signed, ci-no-td

#7152 [ALI] adds AUTH_GH_ORG and AUTH_GH_REPO to set/restrict authentication and management for a specific org/repo
  terraform-aws-github-runner/main.tf
  terraform-aws-github-runner/modules/runners/lambdas/runners/Makefile
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/cache.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/config.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/metrics.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/sqs.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/utils.ts
  terraform-aws-github-runner/modules/runners/scale-down.tf
  terraform-aws-github-runner/modules/runners/scale-up-chron.tf
  terraform-aws-github-runner/modules/runners/scale-up.tf
  terraform-aws-github-runner/modules/runners/variables.tf
  terraform-aws-github-runner/variables.tf
Labels: CLA Signed

#7181 [HUD] Create a vLLM S3 profiling traces table to vLLM benchmark dashboard
  torchci/components/benchmark/llms/LLMsBenchmarkPage.tsx
  torchci/components/benchmark/llms/components/VllmArtifactsTable.tsx
  torchci/lib/benchmark/llms/utils/artifacts.ts
  torchci/pages/api/artifacts/index.ts
Labels: CLA Signed

#7194 [BE] Fixing build warnings when building torchci
  torchci/components/TorchAgentPage/ChatHistorySidebar.tsx
  torchci/components/TorchAgentPage/QueryInputSection.tsx
  torchci/components/TorchAgentPage/WelcomeSection.tsx
  torchci/components/TorchAgentPage/messageProcessor.ts
  torchci/components/TorchAgentPage/styles.ts
  torchci/components/TorchAgentPage/useMessageProcessor.ts
  torchci/components/TorchAgentPage/utils.tsx
  torchci/components/benchmark/compilers/BenchmarkLogs.tsx
  torchci/components/benchmark/compilers/ModelGraphPanel.tsx
  torchci/pages/api/benchmark/list_commits.ts
  torchci/pages/api/torchagent-get-chat-history/index.ts
  torchci/pages/api/torchagent-get-history/index.ts
  torchci/pages/api/torchagent-share.ts
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
Labels: CLA Signed

#7192 Extend Dr.CI API to support meta-pytorch org
  .github/workflows/update-drci-comments.yml
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#7187 [autorevert] introduce RevertAction.RUN_LOG with deduplication on write
  aws/lambda/pytorch-auto-revert/SIGNAL_ACTIONS.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/utils.py
Labels: CLA Signed, ci-no-td

#7183 [autorevert] Configure root logger for AWS lambda
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
Labels: CLA Signed, ci-no-td

#7186 [autorevert] Add hud-like HTML grid rendering for the logged state and `autorevert-checker` subcommand
  aws/lambda/pytorch-auto-revert/README.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/hud_renderer.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/run_state_logger.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert_v2.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/hud.py
Labels: CLA Signed, ci-no-td

#7196 [HUD] [vLLM Profiling] Fix S3 path and add more filters for vLLM Profiling
  torchci/components/benchmark/llms/LLMsBenchmarkPage.tsx
  torchci/components/benchmark/llms/components/ProfilingArtifactsTable.tsx
  torchci/components/benchmark/llms/components/VllmArtifactsTable.tsx
  torchci/lib/benchmark/llms/utils/artifacts.ts
  torchci/pages/api/artifacts/index.ts
Labels: CLA Signed

#7211 Remove sglang/vllm dashboard
  torchci/components/layout/NavBar.tsx
Labels: CLA Signed

#7212 Revert "[BE] Split up download.pytorch.org index update job"
  .github/workflows/update-s3-html.yml
  s3_management/assume-role-output.txt
  s3_management/manage.py
Labels: CLA Signed, ci-no-td

#7215 Make the api response check loose to accept unknown extra keys
  aws/lambda/benchmark_regression_summary_report/common/benchmark_time_series_api_model.py
Labels: CLA Signed

#7210 Gate most of the bot functions only to PyTorch-managed repos
  torchci/lib/bot/autoCcBot.ts
  torchci/lib/bot/autoLabelBot.ts
  torchci/lib/bot/autoLabelCodevTrunk.ts
  torchci/lib/bot/cancelWorkflowsOnCloseBot.ts
  torchci/lib/bot/ciflowPushTrigger.ts
  torchci/lib/bot/codevNoWritePermBot.ts
  torchci/lib/bot/drciBot.ts
  torchci/lib/bot/pytorchBotHandler.ts
  torchci/lib/bot/retryBot.ts
  torchci/lib/bot/stripApprovalBot.ts
  torchci/lib/bot/utils.ts
  torchci/lib/bot/verifyDisableTestIssueBot.ts
  torchci/test/autoCcBot.test.ts
  torchci/test/autoLabelBot.test.ts
  torchci/test/autoLabelCodevTrunk.test.ts
  torchci/test/ciflow-push-trigger.test.ts
  torchci/test/codevNoWritePermBot.test.ts
  torchci/test/labelCommands.test.ts
  torchci/test/retryBot.test.ts
  torchci/test/verifyDisableTestIssue.test.ts
Labels: CLA Signed

#7214 Add hyperlink to new ui
  torchci/components/benchmark/v3/components/benchmarkSideBar/components/BranchDropdown.tsx
  torchci/components/benchmark/v3/components/benchmarkSideBar/components/SideBarMainSection.tsx
  torchci/components/benchmark/v3/components/benchmarkSideBar/components/useUrlSync.tsx
  torchci/components/benchmark/v3/components/common/ToggleSection.tsx
  torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/BenchmarkChartSection.tsx
  torchci/components/benchmark/v3/components/dataRender/components/benchmarkTimeSeries/components/BenchmarkTimeSeriesComparisonSection/BenchmarkTimeSeriesComparisonTableSection.tsx
  torchci/components/benchmark/v3/components/dataRender/fanout/defaultFanoutRenderContent.tsx
  torchci/components/benchmark/v3/configs/configBook.tsx
  torchci/components/benchmark/v3/configs/teams/compilers/config.ts
  torchci/components/uiModules/UMCopyLink.tsx
  torchci/lib/benchmark/api_helper/compilers/type.ts
  torchci/lib/benchmark/store/benchmark_regression_store.ts
  torchci/lib/helpers/urlQuery.ts
Labels: CLA Signed

#7219 [AUTOREVERT] Adds circuit breaker with issue in pytorch/pytorch 'ci: disable-autorevert'
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_circuit_breaker.py
Labels: CLA Signed, ci-no-td

#7224 [autorevert] update failure threshold to 3 for autorevert eligibility
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Labels: CLA Signed, ci-no-td

#7230 [BE] Cleanup split-build logic
  .github/workflows/generate_binary_build_matrix.yml
  .github/workflows/validate-binaries.yml
  .github/workflows/validate-linux-binaries.yml
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed, module: rocm

#7229 Remove functorch docs build job from metrics
  torchci/pages/metrics.tsx
Labels: CLA Signed

#7226 [autorevert] improve restart logic with pacing, cap, and backoff
  aws/lambda/pytorch-auto-revert/SIGNAL_ACTIONS.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_actions.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal_actions.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_workflow_resolver.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
Labels: CLA Signed, ci-no-td

#7234 [BE][EZ] Apply SQL linter to ClickHouse schema foler
  .lintrunner.toml
  clickhouse_db_schema/default.all_query_logs/schema.sql
  clickhouse_db_schema/grafana_alerts/broken_viable_strict.sql
  clickhouse_db_schema/oss_ci_utilization/oss_ci_utilization_summary_report_v1.sql
Labels: CLA Signed

#7235 [autorevert] fix handling for insufficient successes
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Labels: CLA Signed, ci-no-td

#7237 [ROCm] update binary build matrix to 6.4 and 7.0
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
Labels: CLA Signed, module: rocm

#7244 [autorevert] fix local cli
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
Labels: CLA Signed, ci-no-td

#7245 [ROCm] revert binary build matrix for test and release
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed, module: rocm, ci-no-td

#7246 Add Thor support to 13.0 aarch64 domain builds
  tools/pkg-helpers/pytorch_pkg_helpers/cuda.py
Labels: CLA Signed

#7250 [autorever] fix indentation in `fetch_tests_for_job_ids`
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
Labels: CLA Signed

#7239 Add vLLM CI metrics
  torchci/clickhouse_queries/vllm/merges_percentage/params.json
  torchci/clickhouse_queries/vllm/merges_percentage/query.sql
  torchci/components/layout/NavBar.tsx
  torchci/pages/metrics/vllm.tsx
Labels: CLA Signed

#7197 [Easy] Add Helion to hud navbar
  torchci/components/layout/NavBar.tsx
Labels: CLA Signed

#7260 [autorever] exclude unstable jobs
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal_extraction_datasource.py
Labels: CLA Signed
