Repository pytorch/test-infra, pull requests merged in 2025-08, with the labels that each got.

#6873 Migrate upload-s3 action for workflow linux_job_v2
  .github/workflows/linux_job_v2.yml
Labels: CLA Signed

#6971 Add option to generate matrix for getting started page
  .github/workflows/generate_binary_build_matrix.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6973 Fix libtorch nightly binaries links 2
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6964 [ez] Move test times queries to their own folder
  tools/torchci/update_test_times.py
  torchci/clickhouse_queries/test_times/per_class/params.json
  torchci/clickhouse_queries/test_times/per_class/query.sql
  torchci/clickhouse_queries/test_times/per_class_periodic_jobs/params.json
  torchci/clickhouse_queries/test_times/per_class_periodic_jobs/query.sql
  torchci/clickhouse_queries/test_times/per_file/params.json
  torchci/clickhouse_queries/test_times/per_file/query.sql
  torchci/clickhouse_queries/test_times/per_file_periodic_jobs/params.json
  torchci/clickhouse_queries/test_times/per_file_periodic_jobs/query.sql
Labels: CLA Signed

#6961 [ez] Remove old envs from test times json
  tools/torchci/tests/test_update_test_times.py
  tools/torchci/update_test_times.py
  torchci/clickhouse_queries/test_times/job_names_past_month/params.json
  torchci/clickhouse_queries/test_times/job_names_past_month/query.sql
Labels: CLA Signed

#6962 [autorevert] Add workflow restarts
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/do_restart.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
  aws/lambda/pytorch-auto-revert/requirements.txt
Labels: CLA Signed, ci-no-td

#6968 update vs2022 to fix illegal instruction.
  aws/ami/windows/scripts/Installers/Install-VS.ps1
Labels: CLA Signed

#6967 Base64 decode the app secret for pytorch-auto-revert lamba
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
Labels: CLA Signed, ci-no-td

#6975 Release 2.8 Update matrices
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed, module: rocm

#6985 [HUD] Enhance queue time visualization with color coding and sorting
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6982 [autorevert] fix pending job check
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
Labels: CLA Signed, ci-no-td

#6990 [BE] Highlight the selected branch and commit
  torchci/components/benchmark/BranchAndCommitPicker.tsx
  torchci/components/benchmark/HighlightMenu.tsx
Labels: CLA Signed

#6984 [HUD] Remove minihud page
  tools/torchci/check_alerts.py
  torchci/components/layout/NavBar.tsx
  torchci/components/minihud.module.css
  torchci/next.config.js
  torchci/pages/minihud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/styles/globals.css
  torchci/test/mergeCommands.test.ts
Labels: CLA Signed

#6986 [HUD] Add option to filter jobs on main page by regex
  torchci/components/common/RegexButton.tsx
  torchci/components/hud/GroupHudTableHeaders.tsx
  torchci/components/job/JobFilterInput.tsx
  torchci/lib/GeneralUtils.ts
  torchci/lib/types.ts
  torchci/pages/hud/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#6991 Correctly populate metric values for each commit
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
Labels: CLA Signed

#6983 [autorevert] implement autorevert and fix detection logic
  aws/lambda/pytorch-auto-revert/Makefile
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_autorevert_detector.py
  aws/lambda/pytorch-auto-revert/requirements.txt
Labels: CLA Signed, ci-no-td

#6995 Reapply "Support clang in MSVC and removal of Visual Studio 2019"
  aws/ami/windows/scripts/Installers/Install-VS.ps1
  aws/ami/windows/windows.pkr.hcl
Labels: CLA Signed

#6989 [HUD][TTS] Add granularity, time, etc to permalink
  torchci/pages/metrics.tsx
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
Labels: CLA Signed

#6992 Show input and output length on vLLM dashboard
  torchci/clickhouse_queries/oss_ci_benchmark_llms/query.sql
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#6997 [autorevert] Add event logging for autorevert actions
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/event_logger.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
  clickhouse_db_schema/misc.autorevert_events/schema.sql
Labels: CLA Signed, ci-no-td

#6999 [EZ] Replace `pytorch-labs` with `meta-pytorch`
  .github/workflows/trigger_nightly.yml
  aws/lambda/README.md
  tools/torchfix/README.md
Labels: CLA Signed

#7013 [autorevert] Remove some vibes from the code
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/__main__.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/event_logger.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/do_restart.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/restart_checker.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_resolver.py
Labels: CLA Signed, ci-no-td

#6963 Clean up repo analysis, refactor, and add more tools
  tools/analytics/org/.gitignore
  tools/analytics/org/README.md
  tools/analytics/org/analyze_contributors.py
  tools/analytics/org/analyze_repo_info.py
  tools/analytics/org/analyze_runner_usage.py
  tools/analytics/org/cache_manager.py
  tools/analytics/org/github_code_search.py
  tools/analytics/org/remove_pytorch_labs.py
  tools/analytics/org/requirements.txt
Labels: CLA Signed

#6998 Add buildkite-webhook-handler lambda to ingest webhook events from Buildkite
  .github/workflows/_lambda-do-release-runners.yml
  aws/lambda/buildkite-webhook-handler/Makefile
  aws/lambda/buildkite-webhook-handler/README.md
  aws/lambda/buildkite-webhook-handler/lambda_function.py
  aws/lambda/buildkite-webhook-handler/requirements.txt
  aws/lambda/buildkite-webhook-handler/test_lambda_function.py
Labels: CLA Signed

#7015 [autorevert] fix regression
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/workflow_checker.py
Labels: CLA Signed, ci-no-td

#7011 [alerts] HUD failing job alerts handles failures that move across shards and a lot of other changes
  .github/workflows/check-alerts.yml
  tools/torchci/check_alerts.py
  tools/torchci/requirements.txt
  tools/torchci/tests/test_check_alerts.py
Labels: CLA Signed

#7004 Windows AMI: Add possibility to use different owners specified in the filter param
  .github/scripts/validate_scale_config.py
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Labels: CLA Signed

#7017 Fix float16/bfloat16 mix-up on TorchInductor dashboard
  torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
  torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
Labels: CLA Signed

#7023 [autorevert] When checking job status, only expect target job list to be finished, not waiting for all jobs to have finished
  aws/lambda/pytorch-auto-revert/Makefile
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
Labels: CLA Signed, ci-no-td

#7030 Update nvidia cuda 13.0 dependencies
  s3_management/update_dependencies.py
Labels: CLA Signed

#7036 Fix vision build for 3.14 and 3.14t and 3.13t build
  .github/actions/setup-binary-builds/action.yml
Labels: CLA Signed

#7038 Add cuda 13.0 packages to update index script
  s3_management/manage.py
Labels: CLA Signed

#7039 fix cudnn naming for CUDA 13 package
  s3_management/manage.py
Labels: CLA Signed

#7041 Add nvidia-nccl-cu13 pkg
  s3_management/manage.py
Labels: CLA Signed

#7040 [HUD][Test Insights] Better PR view for test counts
  torchci/clickhouse_queries/merge_bases/params.json
  torchci/clickhouse_queries/merge_bases/query.sql
  torchci/components/additionalTestInfo/TestCounts.tsx
  torchci/lib/GeneralUtils.ts
  torchci/pages/api/drci/drci.ts
Labels: CLA Signed

#7043 [autorevert] fix query sorting
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
Labels: CLA Signed, ci-no-td

#7051 Remove python 3.9 binary builds
  tools/scripts/generate_binary_build_matrix.py
  tools/tests/assets/build_matrix_linux_wheel_cuda.json
  tools/tests/assets/build_matrix_linux_wheel_cuda_norocm.json
  tools/tests/assets/build_matrix_linux_wheel_nocpu.json
  tools/tests/assets/build_matrix_linux_wheel_xpu.json
  tools/tests/assets/build_matrix_macos_wheel.json
  tools/tests/assets/build_matrix_windows_wheel_cuda.json
  tools/tests/assets/build_matrix_windows_wheel_xpu.json
Labels: CLA Signed, module: rocm

#7048 [ez][CH] s32ch script: automatically create a stored data file if not given
  tools/rockset_migration/s32ch.py
Labels: CLA Signed

#7044 [HUD] Upgrade yarn packages: next, next-auth, @mui
  torchci/app/v2/benchmark/v3/page.tsx
  torchci/app/v2/benchmark/v3/regression/page.tsx
  torchci/components/benchmark/compilers/ModelGraphPanel.tsx
  torchci/components/benchmark/compilers/ModelPanel.tsx
  torchci/components/benchmark/compilers/SummaryGraphPanel.tsx
  torchci/components/benchmark/compilers/SummaryPanel.tsx
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
  torchci/components/benchmark/tritonbench/TimeSeries.tsx
  torchci/components/queueTimeAnalysis/components/pickers/DateRangePicker.tsx
  torchci/lib/RevertModal.tsx
  torchci/next-env.d.ts
  torchci/next.config.js
  torchci/package.json
  torchci/pages/api/drci/drci.ts
  torchci/pages/api/job_annotation/[repoOwner]/[repoName]/[annotation].ts
  torchci/pages/api/log_annotation/[repoOwner]/[repoName]/[annotation].ts
  torchci/pages/benchmark/[suite]/[compiler]/[[...page]].tsx
  torchci/pages/build_time_metrics.tsx
  torchci/pages/cost_analysis.tsx
  torchci/pages/disabled.tsx
  torchci/pages/kpis.tsx
  torchci/pages/metrics.tsx
  torchci/pages/nightlies.tsx
  torchci/pages/reliability/[repoOwner]/[repoName]/[[...page]].tsx
  torchci/pages/sli.tsx
  torchci/pages/torchbench/userbenchmark.tsx
  torchci/pages/tts/[repoOwner]/[repoName]/[branch]/[[...page]].tsx
  torchci/yarn.lock
Labels: CLA Signed

#7054 Silent the annotation error when getting docker_hub_readonly_token secret
  .github/actions/calculate-docker-image/action.yml
Labels: CLA Signed

#7042 [autorevert] refactoring: extract Signal, decouple pattern detection
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/signal.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/tests/test_signal.py
Labels: CLA Signed, ci-no-td

#7056 enable vllm test to trigger in hud
  torchci/components/commit/WorkflowDispatcher.tsx
Labels: CLA Signed

#7016 [bc-linter] Add BC Linter configuration support
  .github/actions/bc-lint/action.yml
  .github/workflows/bc-linter-tests.yml
  tools/stronghold/docs/bc_linter_config.md
  tools/stronghold/requirements.runtime.txt
  tools/stronghold/requirements.txt
  tools/stronghold/src/api/__init__.py
  tools/stronghold/src/api/ast.py
  tools/stronghold/src/api/checker.py
  tools/stronghold/src/api/compatibility.py
  tools/stronghold/src/api/config.py
  tools/stronghold/tests/api/test_ast.py
  tools/stronghold/tests/api/test_compatibility.py
  tools/stronghold/tests/api/test_config.py
  tools/stronghold/tests/api/test_config_loader.py
  tools/stronghold/tests/api/test_path_globs.py
Labels: CLA Signed

#7059 Add sbsa CUDA 13.0 domain builds
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#7063 Update scale-config with Windows AMI tests CUDA 13.0
  .github/canary-scale-config.yml
  .github/lf-canary-scale-config.yml
  .github/lf-scale-config.yml
  .github/scale-config.yml
Labels: CLA Signed

#7065 drci: Remove OH link
  torchci/lib/drciUtils.ts
  torchci/test/drci.test.ts
  torchci/test/drciBot.test.ts
Labels: CLA Signed

#7058 [HUD] SGLang benchmark integration
  torchci/components/benchmark/llms/components/LLMsGraphPanel.tsx
  torchci/components/benchmark/llms/components/LLMsSummaryPanel.tsx
  torchci/components/layout/NavBar.tsx
  torchci/lib/benchmark/llms/common.ts
  torchci/lib/benchmark/llms/utils/llmUtils.ts
Labels: CLA Signed

#7064 [autoscalers] Only use auth to download github files if needed
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/gh-runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up-chron.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#7066 [flakybot] Add xpu in support platforms
  torchci/lib/flakyBot/utils.ts
Labels: CLA Signed

#7018 [BE] Upgrade XPU support package to 2025.2 in Windows CICD
  .github/scripts/install_xpu.bat
  .github/workflows/build_wheels_windows.yml
Labels: CLA Signed

#7071 Fix vLLM workflow trigger and add few others
  torchci/components/commit/WorkflowDispatcher.tsx
Labels: CLA Signed
