Repository pytorch/test-infra, pull requests merged in 2025-07, with the labels that each got.

#6881 [BE] Set up new HUD strucutre with nextjs app structure
  torchci/app/v2/README.md
  torchci/app/v2/benchmark/v3/layout.tsx
  torchci/app/v2/benchmark/v3/page.tsx
  torchci/app/v2/benchmark/v3/regression/layout.tsx
  torchci/app/v2/benchmark/v3/regression/page.tsx
  torchci/app/v2/components/rootUxComponents/hudNavToolBar.tsx
  torchci/app/v2/layout.tsx
  torchci/app/v2/page.tsx
  torchci/components/uiModules/UMComparisonTable.tsx
  torchci/next-env.d.ts
  torchci/tsconfig.json
Labels: CLA Signed

#6882 Add revert category extractionand exclude `ghfirst` reverts from stats
  aws/lambda/pytorch-auto-revert/.env.example
  aws/lambda/pytorch-auto-revert/README.md
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/autorevert_checker.py
  aws/lambda/pytorch-auto-revert/pytorch_auto_revert/testers/autorevert.py
Labels: CLA Signed, ci-no-td

#6883 tools: Update nightly version to 2.9.0
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6884 [ez][HUD] Filter out upload test stats in hud query
  torchci/clickhouse_queries/hud_query/query.sql
Labels: CLA Signed

#6862 [ez][CH] Rename some schemas to include the database
  clickhouse_db_schema/benchmark.oss_ci_benchmark_v3/schema.sql
  clickhouse_db_schema/default.all_query_logs/schema.sql
  clickhouse_db_schema/misc.oss_ci_cur/schema.sql
  clickhouse_db_schema/misc.oss_ci_queue_time_histogram/schema.sql
Labels: CLA Signed

#6903 lint: Add s3_management to PYFMT
  .lintrunner.toml
  s3_management/backup_conda.py
  s3_management/manage.py
  s3_management/update_dependencies.py
Labels: CLA Signed

#6909 [ez][CH] Fix infra_metrics.cloud.watch_metrics schema: use DateTime64
  aws/lambda/clickhouse-replicator-s3/lambda_function.py
  clickhouse_db_schema/infra_metrics.cloudwatch_metrics/schema.sql
Labels: CLA Signed

#6910 [ez][HUD] Filter out more workflow_event trigger jobs from hud query
  torchci/clickhouse_queries/hud_query/query.sql
Labels: CLA Signed

#6912 Add file status to tutorial statistics
  .github/scripts/get_tutorials_stats.py
Labels: CLA Signed

#6924 Update ``trigger_nightly.yml`` to add torchtitan
  .github/workflows/trigger_nightly.yml
Labels: CLA Signed

#6925 Revert "Add miniconda install=true to build_wheels_macos.yml"
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed, ci-no-td

#6922 [HUD] Use stacks for WorkflowBox
  torchci/components/commit/WorkflowBox.tsx
Labels: CLA Signed

#6927 [BE] Limit trunk failure alerts to viable-strict breaking failures
  .github/workflows/check-alerts.yml
  tools/torchci/check_alerts.py
Labels: CLA Signed

#6929 [BE] Stop monitoring builder job status
  .github/workflows/check-alerts.yml
Labels: CLA Signed

#6930 runners: Move runner removal logic up
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts
Labels: CLA Signed

#6928 [BE] Fix lintrunner init for uv based environments
  tools/linter/adapters/pip_init.py
Labels: CLA Signed

#6932 runners: Remove debug logging for listRunners
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Labels: CLA Signed

#6885 runners: Add expiration policy to SSM parameters
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
Labels: CLA Signed

#6923 [ez] Adding results from B200 benchmark to TorchInductor dashboard
  torchci/components/benchmark/compilers/common.tsx
Labels: CLA Signed

#6938 [EZ] Fix TorchInductor CH queries for A100
  torchci/clickhouse_queries/compilers_benchmark_performance/query.sql
  torchci/clickhouse_queries/compilers_benchmark_performance_branches/query.sql
Labels: CLA Signed

#6936 Remove ROCm docker image default in linux_job_v2.yml
  .github/workflows/linux_job_v2.yml
Labels: CLA Signed, module: rocm, ciflow/rocm

#6920 [BE][HUD] Create unified CommitInfo component
  torchci/components/commit/CommitInfo.tsx
  torchci/pages/[repoOwner]/[repoName]/commit/[sha].tsx
  torchci/pages/[repoOwner]/[repoName]/pull/[prNumber].tsx
Labels: CLA Signed

#6937 [ez][lint] Make inclusion path for mypy slightly broader
  .github/scripts/benchmarks/gather_runners_info.py
  .lintrunner.toml
Labels: CLA Signed

#6905 [CI] Remove sarif upload in lint
  .github/workflows/lint.yml
Labels: CLA Signed

#6919 [HUD] Selector for workflow id in commit and PR pages
  torchci/clickhouse_queries/commit_jobs_query/params.json
  torchci/clickhouse_queries/commit_jobs_query/query.sql
  torchci/components/commit/CommitInfo.tsx
  torchci/components/commit/CommitStatus.tsx
  torchci/components/commit/WorkflowBox.tsx
  torchci/lib/fetchCommit.ts
  torchci/pages/api/[repoOwner]/[repoName]/commit/[sha].ts
Labels: CLA Signed

#6942 [BE][HUD] Improve dropdown behavior on touch devices
  torchci/components/layout/NavBar.module.css
  torchci/components/layout/NavBar.tsx
  torchci/styles/globals.css
Labels: CLA Signed

#6944 [BE][HUD] Enhance navbar responsiveness
  torchci/components/layout/NavBar.module.css
  torchci/components/layout/NavBar.tsx
Labels: CLA Signed

#6941 update nvidia-container-toolkit to 1.17.8
  .github/actions/setup-nvidia/action.yml
Labels: CLA Signed

#6878 Util UI for allocated memory
  torchci/clickhouse_queries/oss_ci_util/oss_ci_list_util_stats/query.sql
  torchci/components/utilization/JobUtilizationPage/JobUtilizationPage.tsx
  torchci/components/utilization/JobUtilizationPage/helper.ts
  torchci/components/utilization/WorkflowUtilizationPage/WorkflowUtilizationPage.tsx
  torchci/components/utilization/components/TestSectionView/RankTestView/RankTestView.tsx
  torchci/lib/utilization/fetchListUtilizationMetadataInfo.ts
  torchci/lib/utilization/fetchUtilization.ts
  torchci/lib/utilization/types.ts
Labels: CLA Signed

#6947 Move all viable/strict blocking jobs closer to the beginning
  torchci/lib/JobClassifierUtil.ts
Labels: CLA Signed

#6950 Revert "Cherry Pick of M1 build #6847"
  .github/workflows/build_wheels_macos.yml
Labels: CLA Signed, ci-no-td

#6865 Update Windows Arm64 image
  .github/scripts/winarm64/bootstrap_buildtools.sh
  .github/workflows/build_wheels_windows.yml
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6951 Fix libtorch file naming in matrix
  tools/scripts/generate_binary_build_matrix.py
Labels: CLA Signed

#6945 [HUD] Fix SLI page scroll reset and navigation hijacking
  torchci/pages/sli.tsx
Labels: CLA Signed

#6957 [HUD] Add merge retry rate calculation metric
  torchci/clickhouse_queries/merge_retry_rate/params.json
  torchci/clickhouse_queries/merge_retry_rate/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed

#6955 [BE] Use info logs for normal operations
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.test.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/runners.ts
  terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts
Labels: CLA Signed

#6956 [HUD] Add average PR landing time metric
  torchci/clickhouse_queries/pr_landing_time_avg/params.json
  torchci/clickhouse_queries/pr_landing_time_avg/query.sql
  torchci/pages/metrics.tsx
Labels: CLA Signed
